var stimuli_a_ND = [
  {
    "s1": "A new professor was hired to teach philosophy, and he was supposed to be really sharp.",
    "s2": "When Allen asked several questions, the professor offered incisive and knowledgeable answers.",
    "s3": "Allen said:",
    "full_context": "A new professor was hired to teach philosophy, and he was supposed to be really sharp.When Allen asked several questions, the professor offered incisive and knowledgeable answers.Allen said:",
    "tf_question": "Allen thinks the professor is stupid.",
    "t1": "That guy",
    "t2": "is brilliant",
    "t3": "at answering questions.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Allen thinks the professor is stupid.",
    "CorrectResponse": "F",
    "item": "EXP1",
    data: {item: 'EXP1', condition: 'literal praise'}
  },
  {
    "s1": "Alice told her roommate how afraid she was of taking a required calculus class, because she was sure she would fail.",
    "s2": "When the final grades were posted, Alice saw she had received an A.",
    "s3": "Alice turned to her roommate and said:",
    "full_context": "Alice told her roommate how afraid she was of taking a required calculus class, because she was sure she would fail.When the final grades were posted, Alice saw she had received an A. Alice turned to her roommate and said:",
    "tf_question": "Alice thinks her math grade is great.",
    "t1": "My math grades",
    "t2": "are bad",
    "t3": "these days.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Alice thinks her math grade is great.",
    "CorrectResponse": "T",
    "item": "EXP2",
    data: {item: 'EXP2', condition: 'ironic praise'}
  },
  {
    "s1": "Alicia and her co-worker were social workers who were sent out to visit a family they were told lived in abject poverty.",
    "s2": "When they arrived they found themselves at a large comfortable home.",
    "s3": "Alicia said:",
    "full_context": "Alicia and her co-worker were social workers who were sent out to visit a family they were told lived in abject poverty.When they arrived they found themselves at a large comfortable home.Alicia said:",
    "tf_question": "Alicia thinks the living conditions are good.",
    "t1": "These living conditions",
    "t2": "are terrible",
    "t3": "to see.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Alicia thinks the living conditions are good.",
    "CorrectResponse": "T",
    "item": "EXP3",
    data: {item: 'EXP3', condition: 'ironic praise'}
  },
  {
    "s1": "Audrey and her husband went on a discount cruise in the Caribbean and they expected very little because the trip was so cheap.",
    "s2": "When they arrived, they found that the cruise ship was bare and their cabin was small and uncomfortable.",
    "s3": "Audrey said:",
    "full_context": "Audrey and her husband went on a discount cruise in the Caribbean and they expected very little because the trip was so cheap.When they arrived, they found that the cruise ship was bare and their cabin was small and uncomfortable.Audrey said:",
    "tf_question": "Audrey thinks the cruise ship is horrible.",
    "t1": "We",
    "t2": "are suffering",
    "t3": "on this cruise.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 400,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Audrey thinks the cruise ship is horrible.",
    "CorrectResponse": "T",
    "item": "EXP4",
    data: {item: 'EXP4', condition: 'literal criticism'}
  },
  {
    "s1": "Beth was looking forward to a fun weekend.",
    "s2": "Late on Friday afternoon, Beth's professor told her that there would be no reading assignment for the weekend.",
    "s3": "Beth said:",
    "full_context": "Beth was looking forward to a fun weekend. Late on Friday afternoon, Beth's professor told her that there would be no reading assignment for the weekend.Beth said:",
    "tf_question": "Beth thinks she will have a bad weekend.",
    "t1": "This weekend",
    "t2": "will be pleasant",
    "t3": "for me.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Beth thinks she will have a bad weekend.",
    "CorrectResponse": "F",
    "item": "EXP5",
    data: {item: 'EXP5', condition: 'literal praise'}
  },
  {
    "s1": "Bill's brother said he had too little energy to help Bill paint his den.",
    "s2": "When Bill stopped over at his brother's house later that day, his brother was dozing in the middle of a TV show.",
    "s3": "Bill said:",
    "full_context": "Bill's brother said he had too little energy to help Bill paint his den.When Bill stopped over at his brother's house later that day, his brother was dozing in the middle of a TV show.Bill said:",
    "tf_question": "Bill thinks that his brother is exhausted.",
    "t1": "I see",
    "t2": "you're too tired",
    "t3": "to do much of anything.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "Bill thinks that his brother is exhausted.",
    "CorrectResponse": "T",
    "item": "EXP6",
    data: {item: 'EXP6', condition: 'literal criticism'}
  },
  {
    "s1": "Bob and a co-worker had to fly to Chicago for an important meeting.The plane was scheduled to land at 5 p.m., just in time to make the meeting.",
    "s2": "Bob was very worried that they would miss the beginning of the meeting. The plane arrived an hour late.",
    "s3": "His co-worker said:",
    "full_context": "Bob and a co-worker had to fly to Chicago for an important meeting.The plane was scheduled to land at 5 p.m., just in time to make the meeting.Bob was very worried that they would miss the beginning of the meeting. The plane arrived an hour late. His co-worker said:",
    "tf_question": "Bob's co-worker thinks that they will be on time for the meeting.",
    "t1": "We'll be",
    "t2": "awfully late",
    "t3": "for that meeting.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Bob's co-worker thinks that they will be on time for the meeting.",
    "CorrectResponse": "F",
    "item": "EXP7",
    data: {item: 'EXP7', condition: 'literal criticism'}
  },
  {
    "s1": "Cathy was looking for a clean and quiet apartment and the rental agent told her he had found her the perfect apartment.",
    "s2": "The apartment he showed her was dark and cramped and located right over a railroad track.",
    "s3": "Cathy said:",
    "full_context": "Cathy was looking for a clean and quiet apartment and the rental agent told her he had found her the perfect apartment. The apartment he showed her was dark and cramped and located right over a railroad track.Cathy said:",
    "tf_question": "Cathy thinks the apartment is great.",
    "t1": "This apartment",
    "t2": "is a delight",
    "t3": "to my eyes.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Cathy thinks the apartment is great.",
    "CorrectResponse": "F",
    "item": "EXP8",
    data: {item: 'EXP8', condition: 'ironic criticism'}
  },
  {
    "s1": "Charlie's friend asked Charlie to meet him for dinner to discuss something important and said that he would be sure to be there at seven sharp.",
    "s2": "Charlie arrived at seven o'clock sharp, and so did his friend.",
    "s3": "Charlie said:",
    "full_context": "Charlie's friend asked Charlie to meet him for dinner to discuss something important and said that he would be sure to be there at seven sharp. Charlie arrived at seven o'clock sharp, and so did his friend.Charlie said:",
    "tf_question": "Charlie thinks his friend arrived on time.",
    "t1": "You are",
    "t2": "prompt about",
    "t3": "showing up.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Charlie thinks his friend arrived on time.",
    "CorrectResponse": "T",
    "item": "EXP9",
    data: {item: 'EXP9', condition: 'literal praise'}
  },
  {
    "s1": "Corrine and a friend went to a new movie even though it had been reviewed as the year's worst picture.",
    "s2": "Both found the movie riveting and the ending had them glued to their seats.",
    "s3": "Corrine said:",
    "full_context": "Corrine and a friend went to a new movie even though it had been reviewed as the year's worst picture. Both found the movie riveting and the ending had them glued to their seats. Corrine said:",
    "tf_question": "Corrine thinks the movie was entertaining.",
    "t1": "This movie",
    "t2": "was deadly",
    "t3": "as the review said.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1600,
    "Question": "Corrine thinks the movie was entertaining.",
    "CorrectResponse": "T",
    "item": "EXP10",
    data: {item: 'EXP10', condition: 'ironic praise'}
  },
  {
    "s1": "Frank's cousin considered himself to be very entertaining.",
    "s2": "One evening he told a story about an ordinary shopping trip to the mall, and all the long lines he encountered.",
    "s3": "Frank said:",
    "full_context": "Frank's cousin considered himself to be very entertaining.One evening he told a story about an ordinary shopping trip to the mall, and all the long lines he encountered.Frank said:",
    "tf_question": "Frank thinks his cousin's story about the mall is interesting.",
    "t1": "Your stories",
    "t2": "are fascinating",
    "t3": "to listen to.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Frank thinks his cousin's story about the mall is interesting.",
    "CorrectResponse": "F",
    "item": "EXP11",
    data: {item: 'EXP11', condition: 'ironic criticism'}
  },
  {
    "s1": "Gail's friend asked her to come with her to a lecture on global warming and she went, even though she said she thought it would be of no interest.",
    "s2": "She found the lecture to be deadly, and she did not want to ask any questions.",
    "s3": "Gail's friend said:",
    "full_context": "Gail's friend asked her to come with her to a lecture on global warming and she went, even though she said she thought it would be of no interest. She found the lecture to be deadly, and she did not want to ask any questions.Gail's friend said:",
    "tf_question": "Gail's friend thinks the lecture was exciting.",
    "t1": "That lecture",
    "t2": "was boring",
    "t3": "as you expected.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Gail's friend thinks the lecture was exciting.",
    "CorrectResponse": "F",
    "item": "EXP12",
    data: {item: 'EXP12', condition: 'literal criticism'}
  },
  {
    "s1": "Heidi's boss was looking forward to his weekend getaway.",
    "s2": "Just before he was to leave,  Heidi arrived at his office to pick up a huge load of documents that he had finished",
    "s3": "He said:",
    "full_context": "Heidi's boss was looking forward to his weekend getaway. Just before he was to leave,  Heidi arrived at his office to pick up a huge load of documents that he had finishedHe said:",
    "tf_question": "Heidi's boss thinks he won't enjoy his weekend.",
    "t1": "My getaway",
    "t2": "is going to be nice",
    "t3": "this weekend.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Heidi's boss thinks he won't enjoy his weekend.",
    "CorrectResponse": "F",
    "item": "EXP13",
    data: {item: 'EXP13', condition: 'literal praise'}
  },
  {
    "s1": "It was Jen's first day at her new teaching job and she heard that the students were excited and interested.",
    "s2": "She had prepared a stimulating lecture and the students were alert and asked many thoughtful questions.",
    "s3": "Jen said:",
    "full_context": "It was Jen's first day at her new teaching job and she heard that the students were excited and interested. She had prepared a stimulating lecture and the students were alert and asked many thoughtful questions.Jen said:",
    "tf_question": "Jen thinks the students are enthusiastic.",
    "t1": "These students",
    "t2": "are lively",
    "t3": "in class today.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Jen thinks the students are enthusiastic.",
    "CorrectResponse": "T",
    "item": "EXP14",
    data: {item: 'EXP14', condition: 'literal praise'}
  },
  {
    "s1": "James asked his roommate for help in chemistry.",
    "s2": "James said he could catch on quickly, but it took him two hours to grasp one elementary concept.",
    "s3": "His roommate said:",
    "full_context": "James asked his roommate for help in chemistry. James said he could catch on quickly, but it took him two hours to grasp one elementary concept. His roommate said:",
    "tf_question": "James' roommate thinks James is learning chemistry slowly.",
    "t1": "Chemistry is",
    "t2": "something you're smart",
    "t3": "at picking up.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "James' roommate thinks James is learning chemistry slowly.",
    "CorrectResponse": "T",
    "item": "EXP15",
    data: {item: 'EXP15', condition: 'ironic criticism'}
  },
  {
    "s1": "James told his friend he was sure he would fail his first physics exam.",
    "s2": "When the teacher handed back the grades, she announced that James had gotten a zero.",
    "s3": "His friend said:",
    "full_context": "James told his friend he was sure he would fail his first physics exam.When the teacher handed back the grades, she announced that James had gotten a zero. His friend said:",
    "tf_question": "His friend thinks that James did well on the test.",
    "t1": "You totally",
    "t2": "screwed up",
    "t3": "that test.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "His friend thinks that James did well on the test.",
    "CorrectResponse": "F",
    "item": "EXP16",
    data: {item: 'EXP16', condition: 'literal criticism'}
  },
  {
    "s1": "Jane was at her college reunion, where she ran into many old acquaintances.",
    "s2": "All the people she knew in college were snobby and showed no interest in Jane's life.",
    "s3": "Jane said:",
    "full_context": "Jane was at her college reunion, where she ran into many old acquaintances.All the people she knew in college were snobby and showed no interest in Jane's life.Jane said:",
    "tf_question": "Jane thinks going to the reunion was a mistake.",
    "t1": "Coming to this reunion",
    "t2": "was a fabulous",
    "t3": "thing to do.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Jane thinks going to the reunion was a mistake.",
    "CorrectResponse": "T",
    "item": "EXP17",
    data: {item: 'EXP17', condition: 'ironic criticism'}
  },
  {
    "s1": "Jeanne had postponed her holiday shopping until two days before Christmas.",
    "s2": "Her friend didn't want to go shopping with her because she was sure the crowds would be terrible.",
    "s3": "When they arrived at the mall there was hardly a soul there and Jeanne said:",
    "full_context": "Jeanne had postponed her holiday shopping until two days before Christmas. Her friend didn't want to go shopping with her because she was sure the crowds would be terrible. When they arrived at the mall there was hardly a soul there and Jeanne said:",
    "tf_question": "Jeanne thinks the mall is busy with holiday shoppers.",
    "t1": "The mall",
    "t2": "is packed with",
    "t3": "holiday shoppers.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Jeanne thinks the mall is busy with holiday shoppers.",
    "CorrectResponse": "F",
    "item": "EXP18",
    data: {item: 'EXP18', condition: 'ironic praise'}
  },
  {
    "s1": "Jennifer said she loved greasy, fattening food.",
    "s2": "When her friend opened Jennifer's fridge to get a snack, She found pizza and french fries in the refrigerator and candy and chips in the cabinet",
    "s3": "Her friend said:",
    "full_context": "Jennifer said she loved greasy, fattening food. When her friend opened Jennifer's fridge to get a snack, She found pizza and french fries in the refrigerator and candy and chips in the cabinetHer friend said:",
    "tf_question": "Jennifer's friend thinks that Jennifer eats unhealthy foods.",
    "t1": "I see",
    "t2": "you eat junk",
    "t3": "these days.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Jennifer's friend thinks that Jennifer eats unhealthy foods.",
    "CorrectResponse": "T",
    "item": "EXP19",
    data: {item: 'EXP19', condition: 'literal criticism'}
  },
  {
    "s1": "Jerome and a friend were at a rock concert.",
    "s2": "Jerome said he had seen pictures of the male lead singer, and he was very unattractive and, indeed, when he came on stage, the women in the audience didn't respond at all.",
    "s3": "Jerome's friend said:",
    "full_context": "Jerome and a friend were at a rock concert. Jerome said he had seen pictures of the male lead singer, and he was very unattractive and, indeed, when he came on stage, the women in the audience didn't respond at all.Jerome's friend said:",
    "tf_question": "Jerome's friend thinks that the women are not attracted to the singer.",
    "t1": "He is totally",
    "t2": "unappealing",
    "t3": "to the female sex.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 400,
    "t3_time": 1600,
    "Question": "Jerome's friend thinks that the women are not attracted to the singer.",
    "CorrectResponse": "T",
    "item": "EXP20",
    data: {item: 'EXP20', condition: 'literal criticism'}
  },
  {
    "s1": "Joanne always bragged about her looks.",
    "s2": "On New Year's Eve, she wore a new dress that was slinky and made her waist look really tiny.",
    "s3": "Her roommate watched as she paraded in front of the mirror and said to her:",
    "full_context": "Joanne always bragged about her looks. On New Year's Eve, she wore a new dress that was slinky and made her waist look really tiny.Her roommate watched as she paraded in front of the mirror and said to her:",
    "tf_question": "Joanne's roommate thinks that Joanne looks bad in her new dress.",
    "t1": "That dress",
    "t2": "looks attractive",
    "t3": "on you.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joanne's roommate thinks that Joanne looks bad in her new dress.",
    "CorrectResponse": "F",
    "item": "EXP21",
    data: {item: 'EXP21', condition: 'literal praise'}
  },
  {
    "s1": "Joe had a job interview and his friend told him to be well prepared.",
    "s2": "Joe decided to go out drinking before the interview instead.",
    "s3": "Joe's friend said:",
    "full_context": "Joe had a job interview and his friend told him to be well prepared.Joe decided to go out drinking before the interview instead. Joe's friend said:",
    "tf_question": "Joe's friend thinks Joe is poorly prepared for the interview.",
    "t1": "If you really want the job",
    "t2": "that's a great",
    "t3": "way to get it.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2400,
    "t2_time": 1200,
    "t3_time": 1600,
    "Question": "Joe's friend thinks Joe is poorly prepared for the interview.",
    "CorrectResponse": "T",
    "item": "EXP22",
    data: {item: 'EXP22', condition: 'ironic criticism'}
  },
  {
    "s1": "Joel and his friend had to go to a bad part of town known for a high crime rate.",
    "s2": "When they arrived they found that the neighborhood was a lot like their own: it was clean and filled with respectable looking people.",
    "s3": "Joel said to his friend:",
    "full_context": "Joel and his friend had to go to a bad part of town known for a high crime rate. When they arrived they found that the neighborhood was a lot like their own: it was clean and filled with respectable looking people.Joel said to his friend:",
    "tf_question": "Joel thinks the neighborhood is safe.",
    "t1": "This neighborhood",
    "t2": "looks dangerous",
    "t3": "to me.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joel thinks the neighborhood is safe.",
    "CorrectResponse": "T",
    "item": "EXP23",
    data: {item: 'EXP23', condition: 'ironic praise'}
  },
  {
    "s1": "Joseph said he wouldn't let on about the surprise birthday party on Friday evening for his sister.",
    "s2": "On Friday afternoon, his sister asked him what he was doing that night and Joseph said he had made some plans to see some friends.",
    "s3": "Later, Joseph's mother said:",
    "full_context": "Joseph said he wouldn't let on about the surprise birthday party on Friday evening for his sister. On Friday afternoon, his sister asked him what he was doing that night and Joseph said he had made some plans to see some friends. Later, Joseph's mother said:",
    "tf_question": "Joseph's mother thinks that he is good at keeping secrets.",
    "t1": "You are",
    "t2": "good at",
    "t3": "keeping secrets!",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joseph's mother thinks that he is good at keeping secrets.",
    "CorrectResponse": "T",
    "item": "EXP24",
    data: {item: 'EXP24', condition: 'literal praise'}
  },
  {
    "s1": "Julie took her boyfriend skiing.He had never been on skis, and he said he was afraid he would look like an oaf.",
    "s2": "On his first run, he just skied terribly, turning jerkily and falling at every turn.",
    "s3": "Julie said:",
    "full_context": "Julie took her boyfriend skiing.He had never been on skis, and he said he was afraid he would look like an oaf.On his first run, he just skied terribly, turning jerkily and falling at every turn.Julie said:",
    "tf_question": "Julie thinks that her boyfriend is a good skier.",
    "t1": "You looked",
    "t2": "clumsy",
    "t3": "on that slope.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Julie thinks that her boyfriend is a good skier.",
    "CorrectResponse": "F",
    "item": "EXP25",
    data: {item: 'EXP25', condition: 'literal criticism'}
  },
  {
    "s1": "June took her first roll of film.",
    "s2": "Since she was a beginning photographer, she expected the pictures would come out poorly and, indeed, they came out terribly.",
    "s3": "She said to her friend:",
    "full_context": "June took her first roll of film.Since she was a beginning photographer, she expected the pictures would come out poorly and, indeed, they came out terribly.She said to her friend:",
    "tf_question": "June thinks she is a bad photographer",
    "t1": "I guess",
    "t2": "I'm bad",
    "t3": "at this.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "June thinks she is a bad photographer",
    "CorrectResponse": "T",
    "item": "EXP26",
    data: {item: 'EXP26', condition: 'literal criticism'}
  },
  {
    "s1": "Kelly's classmate asked him to explain the calculus assignment to him.",
    "s2": "Instead of explaining things, Kelly mostly bragged about how smart he was.",
    "s3": "His classmate said:",
    "full_context": "Kelly's classmate asked him to explain the calculus assignment to him. Instead of explaining things, Kelly mostly bragged about how smart he was. His classmate said:",
    "tf_question": "Kelly's classmate thinks Kelly's instruction was worthwhile.",
    "t1": "You are",
    "t2": "helpful",
    "t3": "to have around.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Kelly's classmate thinks Kelly's instruction was worthwhile.",
    "CorrectResponse": "F",
    "item": "EXP27",
    data: {item: 'EXP27', condition: 'ironic criticism'}
  },
  {
    "s1": "Ken reluctantly took an office job as a temp because he really needed money.",
    "s2": "He told his friend the work would probably be mindless and low-level work and, indeed, his first assignment was boring and unchallenging.",
    "s3": "Ken said to his friend:",
    "full_context": "Ken reluctantly took an office job as a temp because he really needed money.He told his friend the work would probably be mindless and low-level work and, indeed, his first assignment was boring and unchallenging.Ken said to his friend:",
    "tf_question": "Ken thinks that the temp work is dull.",
    "t1": "This temp work",
    "t2": "was a bad",
    "t3": "choice for me.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Ken thinks that the temp work is dull.",
    "CorrectResponse": "T",
    "item": "EXP28",
    data: {item: 'EXP28', condition: 'literal criticism'}
  },
  {
    "s1": "Kevin heard that his new roommate was a real stand-up comedian.",
    "s2": "The first day they met, his new roommate made one hilarious joke after another.",
    "s3": "Kevin said:",
    "full_context": "Kevin heard that his new roommate was a real stand-up comedian.The first day they met, his new roommate made one hilarious joke after another. Kevin said:",
    "tf_question": "Kevin thinks the jokes are dull.",
    "t1": "The jokes he tells",
    "t2": "are the funniest",
    "t3": "I've ever heard.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Kevin thinks the jokes are dull.",
    "CorrectResponse": "F",
    "item": "EXP29",
    data: {item: 'EXP29', condition: 'literal praise'}
  },
  {
    "s1": "Marcie bought a used car for a very low price.",
    "s2": "She took it to her mechanic for a tune-up, and told him about the great deal she had gotten on the car.",
    "s3": "After he had checked the car, he told her that it had an excellent engine and excellent brakes, and he commented:",
    "full_context": "Marcie bought a used car for a very low price. She took it to her mechanic for a tune-up, and told him about the great deal she had gotten on the car. After he had checked the car, he told her that it had an excellent engine and excellent brakes, and he commented:",
    "tf_question": "The mechanic thinks Marcie made a good purchase.",
    "t1": "You got",
    "t2": "a bargain",
    "t3": "on this one.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "The mechanic thinks Marcie made a good purchase.",
    "CorrectResponse": "T",
    "item": "EXP30",
    data: {item: 'EXP30', condition: 'literal praise'}
  },
  {
    "s1": "Marco wanted to attend a lecture about job hunting, but his friend resisted, saying that the talk would be of no help at all.",
    "s2": "Still, Marco dragged his friend along.",
    "s3": "At the lecture, his friend got a great lead on a dream job and said:",
    "full_context": "Marco wanted to attend a lecture about job hunting, but his friend resisted, saying that the talk would be of no help at all.Still, Marco dragged his friend along.At the lecture, his friend got a great lead on a dream job and said:",
    "tf_question": "Marco's friend thinks the lecture was helpful.",
    "t1": "Going to that talk",
    "t2": "was a waste of time",
    "t3": "for me.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Marco's friend thinks the lecture was helpful.",
    "CorrectResponse": "T",
    "item": "EXP31",
    data: {item: 'EXP31', condition: 'ironic praise'}
  },
  {
    "s1": "Maryellen expected to rough it when she went camping on a remote island off the coast of Maine.",
    "s2": "When she arrived, she found camping grounds with running water and hot showers.",
    "s3": "Maryellen said:",
    "full_context": "Maryellen expected to rough it when she went camping on a remote island off the coast of Maine. When she arrived, she found camping grounds with running water and hot showers.Maryellen said:",
    "tf_question": "Maryellen thinks the camping facilities are good.",
    "t1": "Life is going",
    "t2": "to be primitive",
    "t3": "on this vacation.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Maryellen thinks the camping facilities are good.",
    "CorrectResponse": "T",
    "item": "EXP32",
    data: {item: 'EXP32', condition: 'ironic praise'}
  },
  {
    "s1": "Matt was doing his comedy act at a nightclub's amateur night",
    "s2": "His friends had told him that his jokes were always terrific and during his act the crowd roared with laughter.",
    "s3": "Matt said:",
    "full_context": "Matt was doing his comedy act at a nightclub's amateur night His friends had told him that his jokes were always terrific and during his act the crowd roared with laughter.Matt said:",
    "tf_question": "Matt thinks his jokes were boring.",
    "t1": "My friends",
    "t2": "were right",
    "t3": "about my jokes.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Matt thinks his jokes were boring.",
    "CorrectResponse": "F",
    "item": "EXP33",
    data: {item: 'EXP33', condition: 'literal praise'}
  },
  {
    "s1": "Mike and his friend were watching an interview with a famous artist who  said that his son had exceptional talent in drawing.",
    "s2": "The artist held up a drawing his three-year-old son had made.",
    "s3": "It was just a simple scribble and Mike said:",
    "full_context": "Mike and his friend were watching an interview with a famous artist who  said that his son had exceptional talent in drawing. The artist held up a drawing his three-year-old son had made.It was just a simple scribble and Mike said:",
    "tf_question": "Mike thinks the drawing is good for a three-year-old.",
    "t1": "That kid",
    "t2": "is a prodigy",
    "t3": "in the visual arts.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1600,
    "Question": "Mike thinks the drawing is good for a three-year-old.",
    "CorrectResponse": "F",
    "item": "EXP34",
    data: {item: 'EXP34', condition: 'ironic criticism'}
  },
  {
    "s1": "Patty was watching a political debate and one of the candidates said he would take on anyone who cared to argue with him.",
    "s2": "When the candidate's positions were challenged by someone from the audience, he stumbled and couldn't answer.",
    "s3": "Patty said:",
    "full_context": "Patty was watching a political debate and one of the candidates said he would take on anyone who cared to argue with him. When the candidate's positions were challenged by someone from the audience, he stumbled and couldn't answer. Patty said:",
    "tf_question": "Patty thinks the politician is a talented public speaker.",
    "t1": "His debating skills",
    "t2": "are terrific",
    "t3": "to watch and learn from.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 2000,
    "Question": "Patty thinks the politician is a talented public speaker.",
    "CorrectResponse": "F",
    "item": "EXP35",
    data: {item: 'EXP35', condition: 'ironic criticism'}
  },
  {
    "s1": "Peter got caught in a meeting late Friday afternoon and he was tensely expecting really bad traffic on the highway home.",
    "s2": "When he got on the highway he found that the traffic was very light and the road nearly deserted.",
    "s3": "Peter said:",
    "full_context": "Peter got caught in a meeting late Friday afternoon and he was tensely expecting really bad traffic on the highway home.When he got on the highway he found that the traffic was very light and the road nearly deserted.Peter said:",
    "tf_question": "Peter thinks that the road is crowded.",
    "t1": "Traffic",
    "t2": "is terrible",
    "t3": "at this time of day.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 400,
    "t2_time": 800,
    "t3_time": 2000,
    "Question": "Peter thinks that the road is crowded.",
    "CorrectResponse": "F",
    "item": "EXP36",
    data: {item: 'EXP36', condition: 'ironic praise'}
  },
  {
    "s1": "Rachel and a friend were on a gambling trip and they hoped to win a pile of money.",
    "s2": "After one hour, Rachel and her friend had lost all their money",
    "s3": "Rachel said:",
    "full_context": "Rachel and a friend were on a gambling trip and they hoped to win a pile of money.After one hour, Rachel and her friend had lost all their money Rachel said:",
    "tf_question": "Rachel thinks gambling is a poor way to make money.",
    "t1": "Gambling is",
    "t2": "a great way",
    "t3": "to make money.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Rachel thinks gambling is a poor way to make money.",
    "CorrectResponse": "T",
    "item": "EXP37",
    data: {item: 'EXP37', condition: 'ironic criticism'}
  },
  {
    "s1": "Ray postponed going to the DMV to get his driver's license because he hated the long lines.",
    "s2": "When he arrived, he was very surprised to see only one person ahead of him in line.",
    "s3": "Ray said:",
    "full_context": "Ray postponed going to the DMV to get his driver's license because he hated the long lines.When he arrived, he was very surprised to see only one person ahead of him in line.Ray said:",
    "tf_question": "Ray thinks the line is long.",
    "t1": "The wait",
    "t2": "is endless",
    "t3": "this morning.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Ray thinks the line is long.",
    "CorrectResponse": "F",
    "item": "EXP38",
    data: {item: 'EXP38', condition: 'ironic praise'}
  },
  {
    "s1": "Sally and her roommate were having a cook-out.",
    "s2": "The forecast predicted that it would clear up, though it had been overcast all day.",
    "s3": "Just as they started the barbecue, it began to rain, and Sally said:",
    "full_context": "Sally and her roommate were having a cook-out. The forecast predicted that it would clear up, though it had been overcast all day.Just as they started the barbecue, it began to rain, and Sally said:",
    "tf_question": "Sally thinks the weather forecast was inaccurate.",
    "t1": "The weather forecast",
    "t2": "is on target",
    "t3": "for our cook-out.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Sally thinks the weather forecast was inaccurate.",
    "CorrectResponse": "T",
    "item": "EXP39",
    data: {item: 'EXP39', condition: 'ironic criticism'}
  },
  {
    "s1": "Sam complained to his mother that he had too much homework, which he said would take him the whole weekend.",
    "s2": "On Saturday morning, he started his work, and was all done in one hour.",
    "s3": "His mother said:",
    "full_context": "Sam complained to his mother that he had too much homework, which he said would take him the whole weekend. On Saturday morning, he started his work, and was all done in one hour.His mother said:",
    "tf_question": "Sam's mother thinks that Sam has a great deal of homework to do",
    "t1": "Your work load",
    "t2": "is overwhelming",
    "t3": "this weekend.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Sam's mother thinks that Sam has a great deal of homework to do",
    "CorrectResponse": "F",
    "item": "EXP40",
    data: {item: 'EXP40', condition: 'ironic praise'}
  },
  {
    "s1": "Sandra was very weight-conscious.",
    "s2": "One month, she gained pounds and she told her friend she was getting fat.",
    "s3": "Her friend said:",
    "full_context": "Sandra was very weight-conscious.One month, she gained pounds and she told her friend she was getting fat.Her friend said:",
    "tf_question": "Sandra's friend thinks that Sandra is thin.",
    "t1": "You are",
    "t2": "so overweight",
    "t3": "these days.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Sandra's friend thinks that Sandra is thin.",
    "CorrectResponse": "F",
    "item": "EXP41",
    data: {item: 'EXP41', condition: 'literal criticism'}
  },
  {
    "s1": "Sarah was looking forward to a pleasant holiday dinner with her entire family.",
    "s2": "At dinner, the fights began, and by the end, everyone was miserable.",
    "s3": "Sarah said:",
    "full_context": "Sarah was looking forward to a pleasant holiday dinner with her entire family.At dinner, the fights began, and by the end, everyone was miserable.Sarah said:",
    "tf_question": "Sarah thinks the evening was tense.",
    "t1": "The atmosphere",
    "t2": "is relaxed",
    "t3": "around this table.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Sarah thinks the evening was tense.",
    "CorrectResponse": "T",
    "item": "EXP42",
    data: {item: 'EXP42', condition: 'ironic criticism'}
  },
  {
    "s1": "Steve's statistics professor had a reputation for giving really difficult exams and refusing to curve the grades.",
    "s2": "The first exam he gave was a breeze and everyone finished long before the hour was up.",
    "s3": "Steve said:",
    "full_context": "Steve's statistics professor had a reputation for giving really difficult exams and refusing to curve the grades.The first exam he gave was a breeze and everyone finished long before the hour was up. Steve said:",
    "tf_question": "Steve thinks the exam was difficult.",
    "t1": "That professor",
    "t2": "is tough",
    "t3": "on his students.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Steve thinks the exam was difficult.",
    "CorrectResponse": "F",
    "item": "EXP43",
    data: {item: 'EXP43', condition: 'ironic praise'}
  },
  {
    "s1": "Steven's friend said he only read trashy novels because he wasn't smart enough to read serious stuff.",
    "s2": "When Steven went to his friend's apartment he saw only romance novels and sports magazines.",
    "s3": "Steven said:",
    "full_context": "Steven's friend said he only read trashy novels because he wasn't smart enough to read serious stuff.When Steven went to his friend's apartment he saw only romance novels and sports magazines.Steven said:",
    "tf_question": "Steven thinks that his friend reads difficult material.",
    "t1": "You stick to",
    "t2": "lightweight",
    "t3": "books and magazines.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Steven thinks that his friend reads difficult material.",
    "CorrectResponse": "F",
    "item": "EXP44",
    data: {item: 'EXP44', condition: 'literal criticism'}
  },
  {
    "s1": "Susan and her roommate were having a party and they thought it would be easy to cook a gourmet meal with a very small budget.",
    "s2": "They had so little money that all they could serve was canned pork and beans",
    "s3": "Susan's roommate said:",
    "full_context": "Susan and her roommate were having a party and they thought it would be easy to cook a gourmet meal with a very small budget. They had so little money that all they could serve was canned pork and beansSusan's roommate said:",
    "tf_question": "Susan's roommate thinks the dinner party was a success.",
    "t1": "Having this dinner party",
    "t2": "on a tight budget",
    "t3": "was a stunning idea!",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1600,
    "t3_time": 1600,
    "Question": "Susan's roommate thinks the dinner party was a success.",
    "CorrectResponse": "F",
    "item": "EXP45",
    data: {item: 'EXP45', condition: 'ironic criticism'}
  },
  {
    "s1": "The students in Annette's class all had to do a group project.",
    "s2": "When it was time to get started, they got to work, and got it done early.",
    "s3": "Annette said:",
    "full_context": "The students in Annette's class all had to do a group project.When it was time to get started, they got to work, and got it done early.Annette said:",
    "tf_question": "Annette thinks they did a good job.",
    "t1": "Our planning",
    "t2": "was excellent",
    "t3": "on this project.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Annette thinks they did a good job.",
    "CorrectResponse": "T",
    "item": "EXP46",
    data: {item: 'EXP46', condition: 'literal praise'}
  },
  {
    "s1": "Tim was bringing a friend to the neighborhood block party and he warned his friend that the party would probably be a deadly bore.",
    "s2": "To everyone's amazement, a famous comedian was at the party, entertaining everyone with his humor.",
    "s3": "Tim's friend said:",
    "full_context": "Tim was bringing a friend to the neighborhood block party and he warned his friend that the party would probably be a deadly bore.To everyone's amazement, a famous comedian was at the party, entertaining everyone with his humor. Tim's friend said:",
    "tf_question": "Tim's friend thinks the party was boring.",
    "t1": "This party",
    "t2": "is dull",
    "t3": "as you predicted.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Tim's friend thinks the party was boring.",
    "CorrectResponse": "F",
    "item": "EXP47",
    data: {item: 'EXP47', condition: 'ironic praise'}
  },
  {
    "s1": "Tony was anxiously awaiting his SAT scores and he knew his parents expected him to do well.",
    "s2": "When his scores arrived, he was pretty thrilled, because his scores were the highest in his class.",
    "s3": "Tony said:",
    "full_context": "Tony was anxiously awaiting his SAT scores and he knew his parents expected him to do well. When his scores arrived, he was pretty thrilled, because his scores were the highest in his class.Tony said:",
    "tf_question": "Tony thinks that his parents will be impressed with his scores.",
    "t1": "My parents",
    "t2": "are going to be",
    "t3": "happy about this.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1600,
    "t3_time": 1200,
    "Question": "Tony thinks that his parents will be impressed with his scores.",
    "CorrectResponse": "T",
    "item": "EXP48",
    data: {item: 'EXP48', condition: 'literal praise'}
  }
]