[
  {
    "s1": "Afflicted with a mysterious skin condition on his behind, Ross seeks advice from Phoebe's herbalist.",
    "s2": "He feels uneasy about exposing his buttocks to the man, but finally he gets convinced and the herbalist gives him some mysterious ointments.",
    "s3": "After two weeks of applying them regularly, Ross says:",
    "full_context": "Afflicted with a mysterious skin condition on his behind, Ross seeks advice from Phoebe's herbalist.He feels uneasy about exposing his buttocks to the man, but finally he gets convinced and the herbalist gives him some mysterious ointments. After two weeks of applying them regularly, Ross says:",
    "tf_question": "It was Phoebe who recommended the doctor to Ross.",
    "t1": "These ointments",
    "t2": "made my butt",
    "t3": "itch even worse than before!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "It was Phoebe who recommended the doctor to Ross.",
    "CorrectResponse": "z",
    "item": "D1",
    data: {item: 'D1', condition: 'distracter'}
  },
  {
    "s1": "Chandler and Joey are with Monica at the beach, where she gets stung by a jellyfish.",
    "s2": "Joey, who saw a feature on the Discovery Channel, suggests peeing on the sting, but gets scared, so Chandler finally does it.",
    "s3": "Monica says to the guys:",
    "full_context": "Chandler and Joey are with Monica at the beach, where she gets stung by a jellyfish.Joey, who saw a feature on the Discovery Channel, suggests peeing on the sting, but gets scared, so Chandler finally does it.Monica says to the guys:",
    "tf_question": "Phoebe got stung by a wasp.",
    "t1": "It finally stopped burning",
    "t2": "and the swelling",
    "t3": "is nearly gone!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Phoebe got stung by a wasp.",
    "CorrectResponse": "{/}",
    "item": "D2",
    data: {item: 'D2', condition: 'distracter'}
  },
  {
    "s1": "Chandler is planning to propose to Monica, but he wants it to be a surprise.",
    "s2": "He keeps telling her that he never wants to get married and she starts to believe it and leaves their apartment all in tears, heading to her ex-boyfriend Richard.",
    "s3": "Chandler says to Joey:",
    "full_context": "Chandler is planning to propose to Monica, but he wants it to be a surprise. He keeps telling her that he never wants to get married and she starts to believe it and leaves their apartment all in tears, heading to her ex-boyfriend Richard. Chandler says to Joey:",
    "tf_question": "Chandler is a fierce opponent of marriage.",
    "t1": "I have to catch her",
    "t2": "as soon as possible",
    "t3": "or she'll be gone for good.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2000,
    "t2_time": 1600,
    "t3_time": 2400,
    "Question": "Chandler is a fierce opponent of marriage.",
    "CorrectResponse": "z",
    "item": "D3",
    data: {item: 'D3', condition: 'distracter'}
  },
  {
    "s1": "Joey and Chandler adopt a baby chick and a duck.",
    "s2": "They are having great fun organising chick and duck races, when Chandler's girlfriend Janice comes to visit him.",
    "s3": "When she sees her boyfriend engaging in such ridiculous activities, she says to Chandler:",
    "full_context": "Joey and Chandler adopt a baby chick and a duck.They are having great fun organising chick and duck races, when Chandler's girlfriend Janice comes to visit him. When she sees her boyfriend engaging in such ridiculous activities, she says to Chandler:",
    "tf_question": "Janice didn't like the idea of keeping chicks and ducks at home.",
    "t1": "I didn't realise",
    "t2": "you've never left",
    "t3": "pre-school!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 400,
    "Question": "Janice didn't like the idea of keeping chicks and ducks at home.",
    "CorrectResponse": "z",
    "item": "D4",
    data: {item: 'D4', condition: 'distracter'}
  },
  {
    "s1": "Joey gets chosen to play the role of Dr. Drake Ramoray, a neurosurgeon on Days of Our Lives after he sleeps with the casting lady.",
    "s2": "However, he makes his friends believe that he\\n got picked only thanks to his remarkable acting skills.",
    "s3": "Chandler says:",
    "full_context": "Joey gets chosen to play the role of Dr. Drake Ramoray, a neurosurgeon on Days of Our Lives after he sleeps with the casting lady.However, he makes his friends believe that he\\n got picked only thanks to his remarkable acting skills. Chandler says:",
    "tf_question": "Joey got picked for the role of Mozart in \"Amadeus\".",
    "t1": "I've never been prouder",
    "t2": "of my best friend Joey",
    "t3": "than today!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Joey got picked for the role of Mozart in \"Amadeus\".",
    "CorrectResponse": "{/}",
    "item": "D5",
    data: {item: 'D5', condition: 'distracter'}
  },
  {
    "s1": "Joey gives Chandler an extremely tacky engraved gold bracelet, telling him that this shall be the symbol of their enduring friendship.",
    "s2": "Chandler pretends he likes the bracelet but never wears it which makes Joey suspicious.",
    "s3": "Joey says to Chandler:",
    "full_context": "Joey gives Chandler an extremely tacky engraved gold bracelet, telling him that this shall be the symbol of their enduring friendship. Chandler pretends he likes the bracelet but never wears it which makes Joey suspicious.Joey says to Chandler:",
    "tf_question": "Chandler gave Joey a gold bracelet.",
    "t1": "I can see",
    "t2": "that you're not wearing",
    "t3": "the bracelet.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1600,
    "t3_time": 800,
    "Question": "Chandler gave Joey a gold bracelet.",
    "CorrectResponse": "z",
    "item": "D6",
    data: {item: 'D6', condition: 'distracter'}
  },
  {
    "s1": "Joey is dating Ross's work colleague Charlie who is a paleonthologist too.",
    "s2": "When the whole group goes to Barbados to accompany Ross on a paleonthologists' conference, it quickly turns out that Joey and Charlie have little in common.",
    "s3": "They decide to break up and Joey is in great pain, so to console him Ross says to him:",
    "full_context": "Joey is dating Ross's work colleague Charlie who is a paleonthologist too.When the whole group goes to Barbados to accompany Ross on a paleonthologists' conference, it quickly turns out that Joey and Charlie have little in common. They decide to break up and Joey is in great pain, so to console him Ross says to him:",
    "tf_question": "Charlie is an ophthalmologist.",
    "t1": "Don't worry,",
    "t2": "maybe you two were just",
    "t3": "not meant to be together.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 2000,
    "Question": "Charlie is an ophthalmologist.",
    "CorrectResponse": "z",
    "item": "D7",
    data: {item: 'D7', condition: 'distracter'}
  },
  {
    "s1": "Monica and Chandler decide not to host Thanksgiving but Phoebe convinces them to by appealing to Monica's competitive nature.",
    "s2": "Chandler helps out for the first time by making Cranberry sauce and surprisingly, Monica lets him.",
    "s3": "The sauce is a disaster, but Monica decides to be supportive, so she says to Chandler:",
    "full_context": "Monica and Chandler decide not to host Thanksgiving but Phoebe convinces them to by appealing to Monica's competitive nature. Chandler helps out for the first time by making Cranberry sauce and surprisingly, Monica lets him.The sauce is a disaster, but Monica decides to be supportive, so she says to Chandler:",
    "tf_question": "Chandler doesn't cook very well.",
    "t1": "Don't worry,",
    "t2": "I'll make my own sauce",
    "t3": "in a minute.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 1200,
    "Question": "Chandler doesn't cook very well.",
    "CorrectResponse": "{/}",
    "item": "D8",
    data: {item: 'D8', condition: 'distracter'}
  },
  {
    "s1": "Monica cooks a gourmet meal for a restaurateur named Steve, who is looking for a new chef.",
    "s2": "Unfortunately, he's stoned and would just as well eat McDonald's french fries as her haute cuisine.",
    "s3": "As a result, Monica doesn't get the job and he says to Rachel:",
    "full_context": "Monica cooks a gourmet meal for a restaurateur named Steve, who is looking for a new chef. Unfortunately, he's stoned and would just as well eat McDonald's french fries as her haute cuisine.As a result, Monica doesn't get the job and he says to Rachel:",
    "tf_question": "Monica prepared french fries to impress the famous restaurateur, Steve.",
    "t1": "I really thought",
    "t2": "I would get",
    "t3": "this job!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Monica prepared french fries to impress the famous restaurateur, Steve.",
    "CorrectResponse": "{/}",
    "item": "D9",
    data: {item: 'D9', condition: 'distracter'}
  },
  {
    "s1": "Monica decides to pay an unexpected visit to her boyfriend Chandler in Tulsa, where he had moved recently for his new job.",
    "s2": "However, he's watching porn on the hotel television and when she arrives he, in panic, switches channels to a shark documentary.",
    "s3": "He leads Monica to believe the sea creatures turn him on and Monica says to him:",
    "full_context": "Monica decides to pay an unexpected visit to her boyfriend Chandler in Tulsa, where he had moved recently for his new job.However, he's watching porn on the hotel television and when she arrives he, in panic, switches channels to a shark documentary. He leads Monica to believe the sea creatures turn him on and Monica says to him:",
    "tf_question": "Monica visited Chandler in his new apartment in Toledo.",
    "t1": "That simply",
    "t2": "can't be true,",
    "t3": "you must be kidding me!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "Monica visited Chandler in his new apartment in Toledo.",
    "CorrectResponse": "{/}",
    "item": "D10",
    data: {item: 'D10', condition: 'distracter'}
  },
  {
    "s1": "Phoebe adopts an orphaned rat family and she invites her new boyfriend David, who is a physicist, to her apartment.",
    "s2": "When David finds out she's keeping rats at home, he is terribly scared and lists to Phoebe all the diseases she can possibly contract from her new pets.",
    "s3": "Phoebe refuses to get rid of them and says to him:",
    "full_context": "Phoebe adopts an orphaned rat family and she invites her new boyfriend David, who is a physicist, to her apartment. When David finds out she's keeping rats at home, he is terribly scared and lists to Phoebe all the diseases she can possibly contract from her new pets. Phoebe refuses to get rid of them and says to him:",
    "tf_question": "Phoebe's boyfriend is a physicist.",
    "t1": "I don't need",
    "t2": "your doctor's talk",
    "t3": "at all!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Phoebe's boyfriend is a physicist.",
    "CorrectResponse": "z",
    "item": "D11",
    data: {item: 'D11', condition: 'distracter'}
  },
  {
    "s1": "Phoebe catches chicken pox just as her old flame Ryan arrives in town on leave from the Navy.",
    "s2": "Even though he hasn't yet had chicken pox, he can't stand to be apart.",
    "s3": "They both spend the rest of the time sick trying to not scratch at the sore, and Ryan says to her:",
    "full_context": "Phoebe catches chicken pox just as her old flame Ryan arrives in town on leave from the Navy.Even though he hasn't yet had chicken pox, he can't stand to be apart.They both spend the rest of the time sick trying to not scratch at the sore, and Ryan says to her:",
    "tf_question": "Ryan has never has chicken pox before.",
    "t1": "I'll go to the drugstore downstairs",
    "t2": "and bring us some ointment",
    "t3": "for the sore spots.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2400,
    "t2_time": 2000,
    "t3_time": 1600,
    "Question": "Ryan has never has chicken pox before.",
    "CorrectResponse": "{/}",
    "item": "D12",
    data: {item: 'D12', condition: 'distracter'}
  },
  {
    "s1": "Phoebe has been a vegetarian for her entire life, but when she gets pregnant with the triplets she feels compelled to finally start eating meat.",
    "s2": "Hardly a day passes without her eating a huge raw steak.",
    "s3": "She says to her friend Rachel:",
    "full_context": "Phoebe has been a vegetarian for her entire life, but when she gets pregnant with the triplets she feels compelled to finally start eating meat. Hardly a day passes without her eating a huge raw steak. She says to her friend Rachel:",
    "tf_question": "Phoebe is pregnant with triplets.",
    "t1": "These babies",
    "t2": "in my womb",
    "t3": "are definitely carnivore!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Phoebe is pregnant with triplets.",
    "CorrectResponse": "{/}",
    "item": "D13",
    data: {item: 'D13', condition: 'distracter'}
  },
  {
    "s1": "Phoebe is discovered by a record producer who wants to make her song \"Smelly Cat\" a video, but who secretly dubs in the voice of a more talented woman.",
    "s2": "Phoebe feels betrayed and she promises to take revenge on the producer.",
    "s3": "She tells her friends:",
    "full_context": "Phoebe is discovered by a record producer who wants to make her song \"Smelly Cat\" a video, but who secretly dubs in the voice of a more talented woman. Phoebe feels betrayed and she promises to take revenge on the producer. She tells her friends:",
    "tf_question": "Phoebe is the author of a famous song: \"Smelly Feet\".",
    "t1": "This awful guy",
    "t2": "simply made a fool",
    "t3": "out of me!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1600,
    "t3_time": 1200,
    "Question": "Phoebe is the author of a famous song: \"Smelly Feet\".",
    "CorrectResponse": "z",
    "item": "D14",
    data: {item: 'D14', condition: 'distracter'}
  },
  {
    "s1": "Phoebe is trying to teach Joey some French for his audition for a theatre play.",
    "s2": "She asks him to repeat the sentence:\"Je m'appelle Claude\", but he keeps mispronouncing it as: \" Je de coup Clow\".",
    "s3": "Phoebe gets irritated and refuses to teach him any longer, saying:",
    "full_context": "Phoebe is trying to teach Joey some French for his audition for a theatre play.She asks him to repeat the sentence:\"Je m'appelle Claude\", but he keeps mispronouncing it as: \" Je de coup Clow\". Phoebe gets irritated and refuses to teach him any longer, saying:",
    "tf_question": "Phoebe is teaching Joey how to speak French.",
    "t1": "I won't teach somebody",
    "t2": "who is utterly",
    "t3": "tone-deaf!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 400,
    "Question": "Phoebe is teaching Joey how to speak French.",
    "CorrectResponse": "z",
    "item": "D15",
    data: {item: 'D15', condition: 'distracter'}
  },
  {
    "s1": "Rachel and Monica had a neighbour upstairs, Mr Heckles, every conversation  with whom broke out into a row.",
    "s2": "However, when he died, he left all his belongings to Monica and Rachel.",
    "s3": "Rachel said to Monica:",
    "full_context": "Rachel and Monica had a neighbour upstairs, Mr Heckles, every conversation  with whom broke out into a row.However, when he died, he left all his belongings to Monica and Rachel.Rachel said to Monica:",
    "tf_question": "Mr Heckles was Monica's grandfather.",
    "t1": "Now I feel so bad",
    "t2": "about us having treated him",
    "t3": "so badly.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2000,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Mr Heckles was Monica's grandfather.",
    "CorrectResponse": "{/}",
    "item": "D16",
    data: {item: 'D16', condition: 'distracter'}
  },
  {
    "s1": "Rachel arrives at Central Perk after running away from her wedding to her fianc√© Barry and moves into her high school friend Monica.",
    "s2": "When Ross, who's had a crush on Rachel since high school, sees her at Monica's, he starts trying to rekindle their relationship.",
    "s3": "Ross says to Rachel:",
    "full_context": "Rachel arrives at Central Perk after running away from her wedding to her fianc√© Barry and moves into her high school friend Monica. When Ross, who's had a crush on Rachel since high school, sees her at Monica's, he starts trying to rekindle their relationship.Ross says to Rachel:",
    "tf_question": "Ross still has feelings for his high school sweetheart Rachel.",
    "t1": "We were really happy",
    "t2": "back then in high school together,",
    "t3": "weren't we?",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 2400,
    "t3_time": 800,
    "Question": "Ross still has feelings for his high school sweetheart Rachel.",
    "CorrectResponse": "{/}",
    "item": "D17",
    data: {item: 'D17', condition: 'distracter'}
  },
  {
    "s1": "Rachel begins working at Bloomingdale's, an upscale department store chain, and Ross becomes jealous of her colleague, Mark.",
    "s2": "Rachel, tired of the constant accusations of infidelity, decides to break up with him.",
    "s3": "Ross says to Rachel:",
    "full_context": "Rachel begins working at Bloomingdale's, an upscale department store chain, and Ross becomes jealous of her colleague, Mark. Rachel, tired of the constant accusations of infidelity, decides to break up with him.Ross says to Rachel:",
    "tf_question": "Rachel took up a job at Bloomingdale's.",
    "t1": "This is the best proof",
    "t2": "that you've been cheating on me",
    "t3": "with this posh twat called Mark!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2000,
    "t2_time": 2400,
    "t3_time": 2400,
    "Question": "Rachel took up a job at Bloomingdale's.",
    "CorrectResponse": "{/}",
    "item": "D18",
    data: {item: 'D18', condition: 'distracter'}
  },
  {
    "s1": "Rachel is going to move to Paris and Ross, realizing  he loves her, chases after her to the airport.",
    "s2": "Rachel realizes she loves him, too, and cancels her flight.",
    "s3": "When the two meet at the airport, she says to him:",
    "full_context": "Rachel is going to move to Paris and Ross, realizing  he loves her, chases after her to the airport.Rachel realizes she loves him, too, and cancels her flight.When the two meet at the airport, she says to him:",
    "tf_question": "Rachel is going to move out ouf New York.",
    "t1": "I want to stay",
    "t2": "with you here",
    "t3": "in New York.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Rachel is going to move out ouf New York.",
    "CorrectResponse": "z",
    "item": "D19",
    data: {item: 'D19', condition: 'distracter'}
  },
  {
    "s1": "Rachel is in labor with Ross's baby and when they are in hospital, Ross's mother gives Ross her engagement ring so that he can propose to Rachel.",
    "s2": "Joey finds Ross's engagement ring on the floor in Rachel's room and he kneels to pick it up.",
    "s3": "Rachel thinks he's proposing and says to him:",
    "full_context": "Rachel is in labor with Ross's baby and when they are in hospital, Ross's mother gives Ross her engagement ring so that he can propose to Rachel.Joey finds Ross's engagement ring on the floor in Rachel's room and he kneels to pick it up.Rachel thinks he's proposing and says to him:",
    "tf_question": "Ross was going to propose to Rachel.",
    "t1": "You're so sweet, Joey,",
    "t2": "let's get married",
    "t3": "right away!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Ross was going to propose to Rachel.",
    "CorrectResponse": "{/}",
    "item": "D20",
    data: {item: 'D20', condition: 'distracter'}
  },
  {
    "s1": "Rachel is known for her lack of cooking skills, but to  prove her friends wrong, she decided to prepare the most\\ndelicious cake for Thanksgiving.",
    "s2": "However, she mixed up two \\ndifferent recipes and instead of strawberry jam, she put pork\\n into the cake.",
    "s3": "Ross said to the rest of the friends:",
    "full_context": "Rachel is known for her lack of cooking skills, but to  prove her friends wrong, she decided to prepare the most\\ndelicious cake for Thanksgiving.However, she mixed up two \\ndifferent recipes and instead of strawberry jam, she put pork\\n into the cake.Ross said to the rest of the friends:",
    "tf_question": "Rachel prepared a Christmas pudding.",
    "t1": "We need to pretend",
    "t2": "that this is the most",
    "t3": "delicious cake ever!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 1200,
    "Question": "Rachel prepared a Christmas pudding.",
    "CorrectResponse": "{/}",
    "item": "D21",
    data: {item: 'D21', condition: 'distracter'}
  },
  {
    "s1": "Ross buys himself a pet monkey called Marcel, but  it turns out that he owns it illegally as he doesn't have a permit.",
    "s2": "He decides to give Marcel to a film-making company and the monkey becomes a film star in California",
    "s3": "After Marcel is gone, Ross says:",
    "full_context": "Ross buys himself a pet monkey called Marcel, but  it turns out that he owns it illegally as he doesn't have a permit. He decides to give Marcel to a film-making company and the monkey becomes a film star in CaliforniaAfter Marcel is gone, Ross says:",
    "tf_question": "Ross bought himself a parrot.",
    "t1": "I miss",
    "t2": "my lovely Marcel",
    "t3": "so much!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Ross bought himself a parrot.",
    "CorrectResponse": "z",
    "item": "D22",
    data: {item: 'D22', condition: 'distracter'}
  },
  {
    "s1": "Ross is compelled to make a choice between his childhood crush Rachel and his current lover Julie.",
    "s2": "He asks Joey and Chandler to help him make a list of the pros and cons of each, and he finally chooses Rachel.",
    "s3": "Rachel, however, finds the list and gets angry with Ross and says to him:",
    "full_context": "Ross is compelled to make a choice between his childhood crush Rachel and his current lover Julie.He asks Joey and Chandler to help him make a list of the pros and cons of each, and he finally chooses Rachel.Rachel, however, finds the list and gets angry with Ross and says to him:",
    "tf_question": "Ross chose Rachel over Julie.",
    "t1": "I can't believe",
    "t2": "you could've done",
    "t3": "such a horrible thing to me!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 2400,
    "Question": "Ross chose Rachel over Julie.",
    "CorrectResponse": "z",
    "item": "D23",
    data: {item: 'D23', condition: 'distracter'}
  },
  {
    "s1": "Ross is preparing for a very important date with his old sweatheart and decides to get a spray-on tan.",
    "s2": "After hearing seemingly straightforward instructions, he gets confused and accidentally gets a double dose on the front of his body and nothing on his back.",
    "s3": "He goes to the date looking ridiculous and the date is a disaster, and after the date he says:",
    "full_context": "Ross is preparing for a very important date with his old sweatheart and decides to get a spray-on tan.After hearing seemingly straightforward instructions, he gets confused and accidentally gets a double dose on the front of his body and nothing on his back. He goes to the date looking ridiculous and the date is a disaster, and after the date he says:",
    "tf_question": "Ross's date didn't like his fake tan.",
    "t1": "I shouldn't have",
    "t2": "got myself this",
    "t3": "spray-on tan.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Ross's date didn't like his fake tan.",
    "CorrectResponse": "{/}",
    "item": "D24",
    data: {item: 'D24', condition: 'distracter'}
  },
  {
    "s1": "A new professor was hired to teach philosophy, and he was supposed to be really sharp.",
    "s2": "When Allen asked several questions, the professor offered incisive and knowledgeable answers.",
    "s3": "Allen said:",
    "full_context": "A new professor was hired to teach philosophy, and he was supposed to be really sharp.When Allen asked several questions, the professor offered incisive and knowledgeable answers.Allen said:",
    "tf_question": "Allen thinks the professor is stupid.",
    "t1": "That guy",
    "t2": "is brilliant",
    "t3": "at answering questions.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Allen thinks the professor is stupid.",
    "CorrectResponse": "z",
    "item": "EXP1",
    data: {item: 'EXP1', condition: 'literal praise'}
  },
  {
    "s1": "Alice told her roommate how afraid she was of taking a required calculus class, because she was sure she would fail.",
    "s2": "When the final grades were posted, Alice saw she had received an A.",
    "s3": "Alice turned to her roommate and said:",
    "full_context": "Alice told her roommate how afraid she was of taking a required calculus class, because she was sure she would fail.When the final grades were posted, Alice saw she had received an A. Alice turned to her roommate and said:",
    "tf_question": "Alice thinks her math grade is great.",
    "t1": "My math grades",
    "t2": "are bad",
    "t3": "these days.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Alice thinks her math grade is great.",
    "CorrectResponse": "{/}",
    "item": "EXP2",
    data: {item: 'EXP2', condition: 'ironic praise'}
  },
  {
    "s1": "Alicia and her co-worker were social workers who were sent out to visit a family they were told lived in abject poverty.",
    "s2": "When they arrived they found themselves at a large comfortable home.",
    "s3": "Alicia said:",
    "full_context": "Alicia and her co-worker were social workers who were sent out to visit a family they were told lived in abject poverty.When they arrived they found themselves at a large comfortable home.Alicia said:",
    "tf_question": "Alicia thinks the living conditions are good.",
    "t1": "These living conditions",
    "t2": "are terrible",
    "t3": "to see.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Alicia thinks the living conditions are good.",
    "CorrectResponse": "{/}",
    "item": "EXP3",
    data: {item: 'EXP3', condition: 'ironic praise'}
  },
  {
    "s1": "Audrey and her husband went on a discount cruise in the Caribbean and they expected very little because the trip was so cheap.",
    "s2": "When they arrived, they found that the cruise ship was bare and their cabin was small and uncomfortable.",
    "s3": "Audrey said:",
    "full_context": "Audrey and her husband went on a discount cruise in the Caribbean and they expected very little because the trip was so cheap.When they arrived, they found that the cruise ship was bare and their cabin was small and uncomfortable.Audrey said:",
    "tf_question": "Audrey thinks the cruise ship is horrible.",
    "t1": "We",
    "t2": "are suffering",
    "t3": "on this cruise.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 400,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Audrey thinks the cruise ship is horrible.",
    "CorrectResponse": "{/}",
    "item": "EXP4",
    data: {item: 'EXP4', condition: 'literal criticism'}
  },
  {
    "s1": "Beth was looking forward to a fun weekend.",
    "s2": "Late on Friday afternoon, Beth's professor told her that there would be no reading assignment for the weekend.",
    "s3": "Beth said:",
    "full_context": "Beth was looking forward to a fun weekend. Late on Friday afternoon, Beth's professor told her that there would be no reading assignment for the weekend.Beth said:",
    "tf_question": "Beth thinks she will have a bad weekend.",
    "t1": "This weekend",
    "t2": "will be pleasant",
    "t3": "for me.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Beth thinks she will have a bad weekend.",
    "CorrectResponse": "z",
    "item": "EXP5",
    data: {item: 'EXP5', condition: 'literal praise'}
  },
  {
    "s1": "Bill's brother said he had too little energy to help Bill paint his den.",
    "s2": "When Bill stopped over at his brother's house later that day, his brother was dozing in the middle of a TV show.",
    "s3": "Bill said:",
    "full_context": "Bill's brother said he had too little energy to help Bill paint his den.When Bill stopped over at his brother's house later that day, his brother was dozing in the middle of a TV show.Bill said:",
    "tf_question": "Bill thinks that his brother is exhausted.",
    "t1": "I see",
    "t2": "you're too tired",
    "t3": "to do much of anything.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "Bill thinks that his brother is exhausted.",
    "CorrectResponse": "{/}",
    "item": "EXP6",
    data: {item: 'EXP6', condition: 'literal criticism'}
  },
  {
    "s1": "Bob and a co-worker had to fly to Chicago for an important meeting.The plane was scheduled to land at 5 p.m., just in time to make the meeting.",
    "s2": "Bob was very worried that they would miss the beginning of the meeting. The plane arrived an hour late.",
    "s3": "His co-worker said:",
    "full_context": "Bob and a co-worker had to fly to Chicago for an important meeting.The plane was scheduled to land at 5 p.m., just in time to make the meeting.Bob was very worried that they would miss the beginning of the meeting. The plane arrived an hour late. His co-worker said:",
    "tf_question": "Bob's co-worker thinks that they will be on time for the meeting.",
    "t1": "We'll be",
    "t2": "awfully late",
    "t3": "for that meeting.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Bob's co-worker thinks that they will be on time for the meeting.",
    "CorrectResponse": "z",
    "item": "EXP7",
    data: {item: 'EXP7', condition: 'literal criticism'}
  },
  {
    "s1": "Cathy was looking for a clean and quiet apartment and the rental agent told her he had found her the perfect apartment.",
    "s2": "The apartment he showed her was dark and cramped and located right over a railroad track.",
    "s3": "Cathy said:",
    "full_context": "Cathy was looking for a clean and quiet apartment and the rental agent told her he had found her the perfect apartment. The apartment he showed her was dark and cramped and located right over a railroad track.Cathy said:",
    "tf_question": "Cathy thinks the apartment is great.",
    "t1": "This apartment",
    "t2": "is a delight",
    "t3": "to my eyes.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Cathy thinks the apartment is great.",
    "CorrectResponse": "z",
    "item": "EXP8",
    data: {item: 'EXP8', condition: 'ironic criticism'}
  },
  {
    "s1": "Charlie's friend asked Charlie to meet him for dinner to discuss something important and said that he would be sure to be there at seven sharp.",
    "s2": "Charlie arrived at seven o'clock sharp, and so did his friend.",
    "s3": "Charlie said:",
    "full_context": "Charlie's friend asked Charlie to meet him for dinner to discuss something important and said that he would be sure to be there at seven sharp. Charlie arrived at seven o'clock sharp, and so did his friend.Charlie said:",
    "tf_question": "Charlie thinks his friend arrived on time.",
    "t1": "You are",
    "t2": "prompt about",
    "t3": "showing up.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Charlie thinks his friend arrived on time.",
    "CorrectResponse": "{/}",
    "item": "EXP9",
    data: {item: 'EXP9', condition: 'literal praise'}
  },
  {
    "s1": "Corrine and a friend went to a new movie even though it had been reviewed as the year's worst picture.",
    "s2": "Both found the movie riveting and the ending had them glued to their seats.",
    "s3": "Corrine said:",
    "full_context": "Corrine and a friend went to a new movie even though it had been reviewed as the year's worst picture. Both found the movie riveting and the ending had them glued to their seats. Corrine said:",
    "tf_question": "Corrine thinks the movie was entertaining.",
    "t1": "This movie",
    "t2": "was deadly",
    "t3": "as the review said.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1600,
    "Question": "Corrine thinks the movie was entertaining.",
    "CorrectResponse": "{/}",
    "item": "EXP10",
    data: {item: 'EXP10', condition: 'ironic praise'}
  },
  {
    "s1": "Frank's cousin considered himself to be very entertaining.",
    "s2": "One evening he told a story about an ordinary shopping trip to the mall, and all the long lines he encountered.",
    "s3": "Frank said:",
    "full_context": "Frank's cousin considered himself to be very entertaining.One evening he told a story about an ordinary shopping trip to the mall, and all the long lines he encountered.Frank said:",
    "tf_question": "Frank thinks his cousin's story about the mall is interesting.",
    "t1": "Your stories",
    "t2": "are fascinating",
    "t3": "to listen to.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Frank thinks his cousin's story about the mall is interesting.",
    "CorrectResponse": "z",
    "item": "EXP11",
    data: {item: 'EXP11', condition: 'ironic criticism'}
  },
  {
    "s1": "Gail's friend asked her to come with her to a lecture on global warming and she went, even though she said she thought it would be of no interest.",
    "s2": "She found the lecture to be deadly, and she did not want to ask any questions.",
    "s3": "Gail's friend said:",
    "full_context": "Gail's friend asked her to come with her to a lecture on global warming and she went, even though she said she thought it would be of no interest. She found the lecture to be deadly, and she did not want to ask any questions.Gail's friend said:",
    "tf_question": "Gail's friend thinks the lecture was exciting.",
    "t1": "That lecture",
    "t2": "was boring",
    "t3": "as you expected.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Gail's friend thinks the lecture was exciting.",
    "CorrectResponse": "z",
    "item": "EXP12",
    data: {item: 'EXP12', condition: 'literal criticism'}
  },
  {
    "s1": "Heidi's boss was looking forward to his weekend getaway.",
    "s2": "Just before he was to leave,  Heidi arrived at his office to pick up a huge load of documents that he had finished",
    "s3": "He said:",
    "full_context": "Heidi's boss was looking forward to his weekend getaway. Just before he was to leave,  Heidi arrived at his office to pick up a huge load of documents that he had finishedHe said:",
    "tf_question": "Heidi's boss thinks he won't enjoy his weekend.",
    "t1": "My getaway",
    "t2": "is going to be nice",
    "t3": "this weekend.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Heidi's boss thinks he won't enjoy his weekend.",
    "CorrectResponse": "z",
    "item": "EXP13",
    data: {item: 'EXP13', condition: 'literal praise'}
  },
  {
    "s1": "It was Jen's first day at her new teaching job and she heard that the students were excited and interested.",
    "s2": "She had prepared a stimulating lecture and the students were alert and asked many thoughtful questions.",
    "s3": "Jen said:",
    "full_context": "It was Jen's first day at her new teaching job and she heard that the students were excited and interested. She had prepared a stimulating lecture and the students were alert and asked many thoughtful questions.Jen said:",
    "tf_question": "Jen thinks the students are enthusiastic.",
    "t1": "These students",
    "t2": "are lively",
    "t3": "in class today.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Jen thinks the students are enthusiastic.",
    "CorrectResponse": "{/}",
    "item": "EXP14",
    data: {item: 'EXP14', condition: 'literal praise'}
  },
  {
    "s1": "James asked his roommate for help in chemistry.",
    "s2": "James said he could catch on quickly, but it took him two hours to grasp one elementary concept.",
    "s3": "His roommate said:",
    "full_context": "James asked his roommate for help in chemistry. James said he could catch on quickly, but it took him two hours to grasp one elementary concept. His roommate said:",
    "tf_question": "James' roommate thinks James is learning chemistry slowly.",
    "t1": "Chemistry is",
    "t2": "something you're smart",
    "t3": "at picking up.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "James' roommate thinks James is learning chemistry slowly.",
    "CorrectResponse": "{/}",
    "item": "EXP15",
    data: {item: 'EXP15', condition: 'ironic criticism'}
  },
  {
    "s1": "James told his friend he was sure he would fail his first physics exam.",
    "s2": "When the teacher handed back the grades, she announced that James had gotten a zero.",
    "s3": "His friend said:",
    "full_context": "James told his friend he was sure he would fail his first physics exam.When the teacher handed back the grades, she announced that James had gotten a zero. His friend said:",
    "tf_question": "His friend thinks that James did well on the test.",
    "t1": "You totally",
    "t2": "screwed up",
    "t3": "that test.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "His friend thinks that James did well on the test.",
    "CorrectResponse": "z",
    "item": "EXP16",
    data: {item: 'EXP16', condition: 'literal criticism'}
  },
  {
    "s1": "Jane was at her college reunion, where she ran into many old acquaintances.",
    "s2": "All the people she knew in college were snobby and showed no interest in Jane's life.",
    "s3": "Jane said:",
    "full_context": "Jane was at her college reunion, where she ran into many old acquaintances.All the people she knew in college were snobby and showed no interest in Jane's life.Jane said:",
    "tf_question": "Jane thinks going to the reunion was a mistake.",
    "t1": "Coming to this reunion",
    "t2": "was a fabulous",
    "t3": "thing to do.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Jane thinks going to the reunion was a mistake.",
    "CorrectResponse": "{/}",
    "item": "EXP17",
    data: {item: 'EXP17', condition: 'ironic criticism'}
  },
  {
    "s1": "Jeanne had postponed her holiday shopping until two days before Christmas.",
    "s2": "Her friend didn't want to go shopping with her because she was sure the crowds would be terrible.",
    "s3": "When they arrived at the mall there was hardly a soul there and Jeanne said:",
    "full_context": "Jeanne had postponed her holiday shopping until two days before Christmas. Her friend didn't want to go shopping with her because she was sure the crowds would be terrible. When they arrived at the mall there was hardly a soul there and Jeanne said:",
    "tf_question": "Jeanne thinks the mall is busy with holiday shoppers.",
    "t1": "The mall",
    "t2": "is packed with",
    "t3": "holiday shoppers.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Jeanne thinks the mall is busy with holiday shoppers.",
    "CorrectResponse": "z",
    "item": "EXP18",
    data: {item: 'EXP18', condition: 'ironic praise'}
  },
  {
    "s1": "Jennifer said she loved greasy, fattening food.",
    "s2": "When her friend opened Jennifer's fridge to get a snack, She found pizza and french fries in the refrigerator and candy and chips in the cabinet",
    "s3": "Her friend said:",
    "full_context": "Jennifer said she loved greasy, fattening food. When her friend opened Jennifer's fridge to get a snack, She found pizza and french fries in the refrigerator and candy and chips in the cabinetHer friend said:",
    "tf_question": "Jennifer's friend thinks that Jennifer eats unhealthy foods.",
    "t1": "I see",
    "t2": "you eat junk",
    "t3": "these days.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Jennifer's friend thinks that Jennifer eats unhealthy foods.",
    "CorrectResponse": "{/}",
    "item": "EXP19",
    data: {item: 'EXP19', condition: 'literal criticism'}
  },
  {
    "s1": "Jerome and a friend were at a rock concert.",
    "s2": "Jerome said he had seen pictures of the male lead singer, and he was very unattractive and, indeed, when he came on stage, the women in the audience didn't respond at all.",
    "s3": "Jerome's friend said:",
    "full_context": "Jerome and a friend were at a rock concert. Jerome said he had seen pictures of the male lead singer, and he was very unattractive and, indeed, when he came on stage, the women in the audience didn't respond at all.Jerome's friend said:",
    "tf_question": "Jerome's friend thinks that the women are not attracted to the singer.",
    "t1": "He is totally",
    "t2": "unappealing",
    "t3": "to the female sex.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 400,
    "t3_time": 1600,
    "Question": "Jerome's friend thinks that the women are not attracted to the singer.",
    "CorrectResponse": "{/}",
    "item": "EXP20",
    data: {item: 'EXP20', condition: 'literal criticism'}
  },
  {
    "s1": "Joanne always bragged about her looks.",
    "s2": "On New Year's Eve, she wore a new dress that was slinky and made her waist look really tiny.",
    "s3": "Her roommate watched as she paraded in front of the mirror and said to her:",
    "full_context": "Joanne always bragged about her looks. On New Year's Eve, she wore a new dress that was slinky and made her waist look really tiny.Her roommate watched as she paraded in front of the mirror and said to her:",
    "tf_question": "Joanne's roommate thinks that Joanne looks bad in her new dress.",
    "t1": "That dress",
    "t2": "looks attractive",
    "t3": "on you.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joanne's roommate thinks that Joanne looks bad in her new dress.",
    "CorrectResponse": "z",
    "item": "EXP21",
    data: {item: 'EXP21', condition: 'literal praise'}
  },
  {
    "s1": "Joe had a job interview and his friend told him to be well prepared.",
    "s2": "Joe decided to go out drinking before the interview instead.",
    "s3": "Joe's friend said:",
    "full_context": "Joe had a job interview and his friend told him to be well prepared.Joe decided to go out drinking before the interview instead. Joe's friend said:",
    "tf_question": "Joe's friend thinks Joe is poorly prepared for the interview.",
    "t1": "If you really want the job",
    "t2": "that's a great",
    "t3": "way to get it.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2400,
    "t2_time": 1200,
    "t3_time": 1600,
    "Question": "Joe's friend thinks Joe is poorly prepared for the interview.",
    "CorrectResponse": "{/}",
    "item": "EXP22",
    data: {item: 'EXP22', condition: 'ironic criticism'}
  },
  {
    "s1": "Joel and his friend had to go to a bad part of town known for a high crime rate.",
    "s2": "When they arrived they found that the neighborhood was a lot like their own: it was clean and filled with respectable looking people.",
    "s3": "Joel said to his friend:",
    "full_context": "Joel and his friend had to go to a bad part of town known for a high crime rate. When they arrived they found that the neighborhood was a lot like their own: it was clean and filled with respectable looking people.Joel said to his friend:",
    "tf_question": "Joel thinks the neighborhood is safe.",
    "t1": "This neighborhood",
    "t2": "looks dangerous",
    "t3": "to me.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joel thinks the neighborhood is safe.",
    "CorrectResponse": "{/}",
    "item": "EXP23",
    data: {item: 'EXP23', condition: 'ironic praise'}
  },
  {
    "s1": "Joseph said he wouldn't let on about the surprise birthday party on Friday evening for his sister.",
    "s2": "On Friday afternoon, his sister asked him what he was doing that night and Joseph said he had made some plans to see some friends.",
    "s3": "Later, Joseph's mother said:",
    "full_context": "Joseph said he wouldn't let on about the surprise birthday party on Friday evening for his sister. On Friday afternoon, his sister asked him what he was doing that night and Joseph said he had made some plans to see some friends. Later, Joseph's mother said:",
    "tf_question": "Joseph's mother thinks that he is good at keeping secrets.",
    "t1": "You are",
    "t2": "good at",
    "t3": "keeping secrets!",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joseph's mother thinks that he is good at keeping secrets.",
    "CorrectResponse": "{/}",
    "item": "EXP24",
    data: {item: 'EXP24', condition: 'literal praise'}
  },
  {
    "s1": "Julie took her boyfriend skiing.He had never been on skis, and he said he was afraid he would look like an oaf.",
    "s2": "On his first run, he just skied terribly, turning jerkily and falling at every turn.",
    "s3": "Julie said:",
    "full_context": "Julie took her boyfriend skiing.He had never been on skis, and he said he was afraid he would look like an oaf.On his first run, he just skied terribly, turning jerkily and falling at every turn.Julie said:",
    "tf_question": "Julie thinks that her boyfriend is a good skier.",
    "t1": "You looked",
    "t2": "clumsy",
    "t3": "on that slope.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Julie thinks that her boyfriend is a good skier.",
    "CorrectResponse": "z",
    "item": "EXP25",
    data: {item: 'EXP25', condition: 'literal criticism'}
  },
  {
    "s1": "June took her first roll of film.",
    "s2": "Since she was a beginning photographer, she expected the pictures would come out poorly and, indeed, they came out terribly.",
    "s3": "She said to her friend:",
    "full_context": "June took her first roll of film.Since she was a beginning photographer, she expected the pictures would come out poorly and, indeed, they came out terribly.She said to her friend:",
    "tf_question": "June thinks she is a bad photographer",
    "t1": "I guess",
    "t2": "I'm bad",
    "t3": "at this.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "June thinks she is a bad photographer",
    "CorrectResponse": "{/}",
    "item": "EXP26",
    data: {item: 'EXP26', condition: 'literal criticism'}
  },
  {
    "s1": "Kelly's classmate asked him to explain the calculus assignment to him.",
    "s2": "Instead of explaining things, Kelly mostly bragged about how smart he was.",
    "s3": "His classmate said:",
    "full_context": "Kelly's classmate asked him to explain the calculus assignment to him. Instead of explaining things, Kelly mostly bragged about how smart he was. His classmate said:",
    "tf_question": "Kelly's classmate thinks Kelly's instruction was worthwhile.",
    "t1": "You are",
    "t2": "helpful",
    "t3": "to have around.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Kelly's classmate thinks Kelly's instruction was worthwhile.",
    "CorrectResponse": "z",
    "item": "EXP27",
    data: {item: 'EXP27', condition: 'ironic criticism'}
  },
  {
    "s1": "Ken reluctantly took an office job as a temp because he really needed money.",
    "s2": "He told his friend the work would probably be mindless and low-level work and, indeed, his first assignment was boring and unchallenging.",
    "s3": "Ken said to his friend:",
    "full_context": "Ken reluctantly took an office job as a temp because he really needed money.He told his friend the work would probably be mindless and low-level work and, indeed, his first assignment was boring and unchallenging.Ken said to his friend:",
    "tf_question": "Ken thinks that the temp work is dull.",
    "t1": "This temp work",
    "t2": "was a bad",
    "t3": "choice for me.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Ken thinks that the temp work is dull.",
    "CorrectResponse": "{/}",
    "item": "EXP28",
    data: {item: 'EXP28', condition: 'literal criticism'}
  },
  {
    "s1": "Kevin heard that his new roommate was a real stand-up comedian.",
    "s2": "The first day they met, his new roommate made one hilarious joke after another.",
    "s3": "Kevin said:",
    "full_context": "Kevin heard that his new roommate was a real stand-up comedian.The first day they met, his new roommate made one hilarious joke after another. Kevin said:",
    "tf_question": "Kevin thinks the jokes are dull.",
    "t1": "The jokes he tells",
    "t2": "are the funniest",
    "t3": "I've ever heard.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Kevin thinks the jokes are dull.",
    "CorrectResponse": "z",
    "item": "EXP29",
    data: {item: 'EXP29', condition: 'literal praise'}
  },
  {
    "s1": "Marcie bought a used car for a very low price.",
    "s2": "She took it to her mechanic for a tune-up, and told him about the great deal she had gotten on the car.",
    "s3": "After he had checked the car, he told her that it had an excellent engine and excellent brakes, and he commented:",
    "full_context": "Marcie bought a used car for a very low price. She took it to her mechanic for a tune-up, and told him about the great deal she had gotten on the car. After he had checked the car, he told her that it had an excellent engine and excellent brakes, and he commented:",
    "tf_question": "The mechanic thinks Marcie made a good purchase.",
    "t1": "You got",
    "t2": "a bargain",
    "t3": "on this one.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "The mechanic thinks Marcie made a good purchase.",
    "CorrectResponse": "{/}",
    "item": "EXP30",
    data: {item: 'EXP30', condition: 'literal praise'}
  },
  {
    "s1": "Marco wanted to attend a lecture about job hunting, but his friend resisted, saying that the talk would be of no help at all.",
    "s2": "Still, Marco dragged his friend along.",
    "s3": "At the lecture, his friend got a great lead on a dream job and said:",
    "full_context": "Marco wanted to attend a lecture about job hunting, but his friend resisted, saying that the talk would be of no help at all.Still, Marco dragged his friend along.At the lecture, his friend got a great lead on a dream job and said:",
    "tf_question": "Marco's friend thinks the lecture was helpful.",
    "t1": "Going to that talk",
    "t2": "was a waste of time",
    "t3": "for me.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Marco's friend thinks the lecture was helpful.",
    "CorrectResponse": "{/}",
    "item": "EXP31",
    data: {item: 'EXP31', condition: 'ironic praise'}
  },
  {
    "s1": "Maryellen expected to rough it when she went camping on a remote island off the coast of Maine.",
    "s2": "When she arrived, she found camping grounds with running water and hot showers.",
    "s3": "Maryellen said:",
    "full_context": "Maryellen expected to rough it when she went camping on a remote island off the coast of Maine. When she arrived, she found camping grounds with running water and hot showers.Maryellen said:",
    "tf_question": "Maryellen thinks the camping facilities are good.",
    "t1": "Life is going",
    "t2": "to be primitive",
    "t3": "on this vacation.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Maryellen thinks the camping facilities are good.",
    "CorrectResponse": "{/}",
    "item": "EXP32",
    data: {item: 'EXP32', condition: 'ironic praise'}
  },
  {
    "s1": "Matt was doing his comedy act at a nightclub's amateur night",
    "s2": "His friends had told him that his jokes were always terrific and during his act the crowd roared with laughter.",
    "s3": "Matt said:",
    "full_context": "Matt was doing his comedy act at a nightclub's amateur night His friends had told him that his jokes were always terrific and during his act the crowd roared with laughter.Matt said:",
    "tf_question": "Matt thinks his jokes were boring.",
    "t1": "My friends",
    "t2": "were right",
    "t3": "about my jokes.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Matt thinks his jokes were boring.",
    "CorrectResponse": "z",
    "item": "EXP33",
    data: {item: 'EXP33', condition: 'literal praise'}
  },
  {
    "s1": "Mike and his friend were watching an interview with a famous artist who  said that his son had exceptional talent in drawing.",
    "s2": "The artist held up a drawing his three-year-old son had made.",
    "s3": "It was just a simple scribble and Mike said:",
    "full_context": "Mike and his friend were watching an interview with a famous artist who  said that his son had exceptional talent in drawing. The artist held up a drawing his three-year-old son had made.It was just a simple scribble and Mike said:",
    "tf_question": "Mike thinks the drawing is good for a three-year-old.",
    "t1": "That kid",
    "t2": "is a prodigy",
    "t3": "in the visual arts.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1600,
    "Question": "Mike thinks the drawing is good for a three-year-old.",
    "CorrectResponse": "z",
    "item": "EXP34",
    data: {item: 'EXP34', condition: 'ironic criticism'}
  },
  {
    "s1": "Patty was watching a political debate and one of the candidates said he would take on anyone who cared to argue with him.",
    "s2": "When the candidate's positions were challenged by someone from the audience, he stumbled and couldn't answer.",
    "s3": "Patty said:",
    "full_context": "Patty was watching a political debate and one of the candidates said he would take on anyone who cared to argue with him. When the candidate's positions were challenged by someone from the audience, he stumbled and couldn't answer. Patty said:",
    "tf_question": "Patty thinks the politician is a talented public speaker.",
    "t1": "His debating skills",
    "t2": "are terrific",
    "t3": "to watch and learn from.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 2000,
    "Question": "Patty thinks the politician is a talented public speaker.",
    "CorrectResponse": "z",
    "item": "EXP35",
    data: {item: 'EXP35', condition: 'ironic criticism'}
  },
  {
    "s1": "Peter got caught in a meeting late Friday afternoon and he was tensely expecting really bad traffic on the highway home.",
    "s2": "When he got on the highway he found that the traffic was very light and the road nearly deserted.",
    "s3": "Peter said:",
    "full_context": "Peter got caught in a meeting late Friday afternoon and he was tensely expecting really bad traffic on the highway home.When he got on the highway he found that the traffic was very light and the road nearly deserted.Peter said:",
    "tf_question": "Peter thinks that the road is crowded.",
    "t1": "Traffic",
    "t2": "is terrible",
    "t3": "at this time of day.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 400,
    "t2_time": 800,
    "t3_time": 2000,
    "Question": "Peter thinks that the road is crowded.",
    "CorrectResponse": "z",
    "item": "EXP36",
    data: {item: 'EXP36', condition: 'ironic praise'}
  },
  {
    "s1": "Rachel and a friend were on a gambling trip and they hoped to win a pile of money.",
    "s2": "After one hour, Rachel and her friend had lost all their money",
    "s3": "Rachel said:",
    "full_context": "Rachel and a friend were on a gambling trip and they hoped to win a pile of money.After one hour, Rachel and her friend had lost all their money Rachel said:",
    "tf_question": "Rachel thinks gambling is a poor way to make money.",
    "t1": "Gambling is",
    "t2": "a great way",
    "t3": "to make money.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Rachel thinks gambling is a poor way to make money.",
    "CorrectResponse": "{/}",
    "item": "EXP37",
    data: {item: 'EXP37', condition: 'ironic criticism'}
  },
  {
    "s1": "Ray postponed going to the DMV to get his driver's license because he hated the long lines.",
    "s2": "When he arrived, he was very surprised to see only one person ahead of him in line.",
    "s3": "Ray said:",
    "full_context": "Ray postponed going to the DMV to get his driver's license because he hated the long lines.When he arrived, he was very surprised to see only one person ahead of him in line.Ray said:",
    "tf_question": "Ray thinks the line is long.",
    "t1": "The wait",
    "t2": "is endless",
    "t3": "this morning.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Ray thinks the line is long.",
    "CorrectResponse": "z",
    "item": "EXP38",
    data: {item: 'EXP38', condition: 'ironic praise'}
  },
  {
    "s1": "Sally and her roommate were having a cook-out.",
    "s2": "The forecast predicted that it would clear up, though it had been overcast all day.",
    "s3": "Just as they started the barbecue, it began to rain, and Sally said:",
    "full_context": "Sally and her roommate were having a cook-out. The forecast predicted that it would clear up, though it had been overcast all day.Just as they started the barbecue, it began to rain, and Sally said:",
    "tf_question": "Sally thinks the weather forecast was inaccurate.",
    "t1": "The weather forecast",
    "t2": "is on target",
    "t3": "for our cook-out.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Sally thinks the weather forecast was inaccurate.",
    "CorrectResponse": "{/}",
    "item": "EXP39",
    data: {item: 'EXP39', condition: 'ironic criticism'}
  },
  {
    "s1": "Sam complained to his mother that he had too much homework, which he said would take him the whole weekend.",
    "s2": "On Saturday morning, he started his work, and was all done in one hour.",
    "s3": "His mother said:",
    "full_context": "Sam complained to his mother that he had too much homework, which he said would take him the whole weekend. On Saturday morning, he started his work, and was all done in one hour.His mother said:",
    "tf_question": "Sam's mother thinks that Sam has a great deal of homework to do",
    "t1": "Your work load",
    "t2": "is overwhelming",
    "t3": "this weekend.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Sam's mother thinks that Sam has a great deal of homework to do",
    "CorrectResponse": "z",
    "item": "EXP40",
    data: {item: 'EXP40', condition: 'ironic praise'}
  },
  {
    "s1": "Sandra was very weight-conscious.",
    "s2": "One month, she gained pounds and she told her friend she was getting fat.",
    "s3": "Her friend said:",
    "full_context": "Sandra was very weight-conscious.One month, she gained pounds and she told her friend she was getting fat.Her friend said:",
    "tf_question": "Sandra's friend thinks that Sandra is thin.",
    "t1": "You are",
    "t2": "so overweight",
    "t3": "these days.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Sandra's friend thinks that Sandra is thin.",
    "CorrectResponse": "z",
    "item": "EXP41",
    data: {item: 'EXP41', condition: 'literal criticism'}
  },
  {
    "s1": "Sarah was looking forward to a pleasant holiday dinner with her entire family.",
    "s2": "At dinner, the fights began, and by the end, everyone was miserable.",
    "s3": "Sarah said:",
    "full_context": "Sarah was looking forward to a pleasant holiday dinner with her entire family.At dinner, the fights began, and by the end, everyone was miserable.Sarah said:",
    "tf_question": "Sarah thinks the evening was tense.",
    "t1": "The atmosphere",
    "t2": "is relaxed",
    "t3": "around this table.",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Sarah thinks the evening was tense.",
    "CorrectResponse": "{/}",
    "item": "EXP42",
    data: {item: 'EXP42', condition: 'ironic criticism'}
  },
  {
    "s1": "Steve's statistics professor had a reputation for giving really difficult exams and refusing to curve the grades.",
    "s2": "The first exam he gave was a breeze and everyone finished long before the hour was up.",
    "s3": "Steve said:",
    "full_context": "Steve's statistics professor had a reputation for giving really difficult exams and refusing to curve the grades.The first exam he gave was a breeze and everyone finished long before the hour was up. Steve said:",
    "tf_question": "Steve thinks the exam was difficult.",
    "t1": "That professor",
    "t2": "is tough",
    "t3": "on his students.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Steve thinks the exam was difficult.",
    "CorrectResponse": "z",
    "item": "EXP43",
    data: {item: 'EXP43', condition: 'ironic praise'}
  },
  {
    "s1": "Steven's friend said he only read trashy novels because he wasn't smart enough to read serious stuff.",
    "s2": "When Steven went to his friend's apartment he saw only romance novels and sports magazines.",
    "s3": "Steven said:",
    "full_context": "Steven's friend said he only read trashy novels because he wasn't smart enough to read serious stuff.When Steven went to his friend's apartment he saw only romance novels and sports magazines.Steven said:",
    "tf_question": "Steven thinks that his friend reads difficult material.",
    "t1": "You stick to",
    "t2": "lightweight",
    "t3": "books and magazines.",
    "condition": "literal criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Steven thinks that his friend reads difficult material.",
    "CorrectResponse": "z",
    "item": "EXP44",
    data: {item: 'EXP44', condition: 'literal criticism'}
  },
  {
    "s1": "Susan and her roommate were having a party and they thought it would be easy to cook a gourmet meal with a very small budget.",
    "s2": "They had so little money that all they could serve was canned pork and beans",
    "s3": "Susan's roommate said:",
    "full_context": "Susan and her roommate were having a party and they thought it would be easy to cook a gourmet meal with a very small budget. They had so little money that all they could serve was canned pork and beansSusan's roommate said:",
    "tf_question": "Susan's roommate thinks the dinner party was a success.",
    "t1": "Having this dinner party",
    "t2": "on a tight budget",
    "t3": "was a stunning idea!",
    "condition": "ironic criticism",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 1600,
    "t3_time": 1600,
    "Question": "Susan's roommate thinks the dinner party was a success.",
    "CorrectResponse": "z",
    "item": "EXP45",
    data: {item: 'EXP45', condition: 'ironic criticism'}
  },
  {
    "s1": "The students in Annette's class all had to do a group project.",
    "s2": "When it was time to get started, they got to work, and got it done early.",
    "s3": "Annette said:",
    "full_context": "The students in Annette's class all had to do a group project.When it was time to get started, they got to work, and got it done early.Annette said:",
    "tf_question": "Annette thinks they did a good job.",
    "t1": "Our planning",
    "t2": "was excellent",
    "t3": "on this project.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Annette thinks they did a good job.",
    "CorrectResponse": "{/}",
    "item": "EXP46",
    data: {item: 'EXP46', condition: 'literal praise'}
  },
  {
    "s1": "Tim was bringing a friend to the neighborhood block party and he warned his friend that the party would probably be a deadly bore.",
    "s2": "To everyone's amazement, a famous comedian was at the party, entertaining everyone with his humor.",
    "s3": "Tim's friend said:",
    "full_context": "Tim was bringing a friend to the neighborhood block party and he warned his friend that the party would probably be a deadly bore.To everyone's amazement, a famous comedian was at the party, entertaining everyone with his humor. Tim's friend said:",
    "tf_question": "Tim's friend thinks the party was boring.",
    "t1": "This party",
    "t2": "is dull",
    "t3": "as you predicted.",
    "condition": "ironic praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Tim's friend thinks the party was boring.",
    "CorrectResponse": "z",
    "item": "EXP47",
    data: {item: 'EXP47', condition: 'ironic praise'}
  },
  {
    "s1": "Tony was anxiously awaiting his SAT scores and he knew his parents expected him to do well.",
    "s2": "When his scores arrived, he was pretty thrilled, because his scores were the highest in his class.",
    "s3": "Tony said:",
    "full_context": "Tony was anxiously awaiting his SAT scores and he knew his parents expected him to do well. When his scores arrived, he was pretty thrilled, because his scores were the highest in his class.Tony said:",
    "tf_question": "Tony thinks that his parents will be impressed with his scores.",
    "t1": "My parents",
    "t2": "are going to be",
    "t3": "happy about this.",
    "condition": "literal praise",
    "list": "ExperimentalA",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1600,
    "t3_time": 1200,
    "Question": "Tony thinks that his parents will be impressed with his scores.",
    "CorrectResponse": "{/}",
    "item": "EXP48",
    data: {item: 'EXP48', condition: 'literal praise'}
  },
  {
    "s1": "Alex went to a restaurant with his girlfriend and ordered an extremely expensive dish called \"A gourmet's dream\" hoping it would be delicious.",
    "s2": "When the waiter arrived with his order, it turned out that the dish was awfully bland and cold.",
    "s3": "Alex said to his girlfriend:",
    "full_context": "Alex went to a restaurant with his girlfriend and ordered an extremely expensive dish called \"A gourmet's dream\" hoping it would be delicious.When the waiter arrived with his order, it turned out that the dish was awfully bland and cold. Alex said to his girlfriend:",
    "tf_question": "Alex thinks the dish is delicious.",
    "t1": "A gourmet's dream",
    "t2": "is an adequate name",
    "t3": "for this exquisite dish!",
    "condition": "ironic criticism",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 1600,
    "t3_time": 1600,
    "Question": "Alex thinks the dish is delicious.",
    "CorrectResponse": "z",
    "item": "P1",
    data: {item: 'P1', condition: 'ironic criticism'}
  },
  {
    "s1": "Christie was going to take an important exam for which she was studying really hard.",
    "s2": "However, on the day of the exam she overslept and didn't manage to make it to the exam on time.",
    "s3": "Christie said to her friend:",
    "full_context": "Christie was going to take an important exam for which she was studying really hard.However, on the day of the exam she overslept and didn't manage to make it to the exam on time. Christie said to her friend:",
    "tf_question": "Christie thinks it's good that she overslept.",
    "t1": "I'm absolutely",
    "t2": "the worst sleepyhead",
    "t3": "you could imagine!",
    "condition": "literal criticism",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Christie thinks it's good that she overslept.",
    "CorrectResponse": "z",
    "item": "P2",
    data: {item: 'P2', condition: 'literal criticism'}
  },
  {
    "s1": "Eddie has been working really hard upon his M.A.thesis.",
    "s2": "One day before the submission deadline, his computer broke down and all files were missing, leaving him with no back-up copy.",
    "s3": "Eddie said to his friend:",
    "full_context": "Eddie has been working really hard upon his M.A.thesis. One day before the submission deadline, his computer broke down and all files were missing, leaving him with no back-up copy.  Eddie said to his friend:",
    "tf_question": "Eddie thinks he was stupid not to make a back-up copy of the file.",
    "t1": "Only clever people like me",
    "t2": "don't make back-up copies",
    "t3": "of important files!",
    "condition": "ironic criticism",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 2000,
    "t2_time": 1600,
    "t3_time": 1200,
    "Question": "Eddie thinks he was stupid not to make a back-up copy of the file.",
    "CorrectResponse": "{/}",
    "item": "P3",
    data: {item: 'P3', condition: 'ironic criticism'}
  },
  {
    "s1": "Frank has been known for his lack of organisational skills.",
    "s2": "However, once he was appointed as a project manager and he handled it wonderfully, leading his team to success.",
    "s3": "His friend said to him:",
    "full_context": "Frank has been known for his lack of organisational skills.However, once he was appointed as a project manager and he handled it wonderfully, leading his team to success. His friend said to him:",
    "tf_question": "Frank's friend thinks he handled the project well.",
    "t1": "You're really",
    "t2": "the worst",
    "t3": "project manager ever!",
    "condition": "ironic praise",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Frank's friend thinks he handled the project well.",
    "CorrectResponse": "{/}",
    "item": "P4",
    data: {item: 'P4', condition: 'ironic praise'}
  },
  {
    "s1": "Lisa, known for her lack of good taste, recommended a hairdresser to her friend, Susan.",
    "s2": "Susan expected the hairdresser to be rather untalented, but actually he made her hair look wonderfully.",
    "s3": "Susan said to Lisa:",
    "full_context": "Lisa, known for her lack of good taste, recommended a hairdresser to her friend, Susan. Susan expected the hairdresser to be rather untalented, but actually he made her hair look wonderfully. Susan said to Lisa:",
    "tf_question": "Susan was disappointed with the hairdresser.",
    "t1": "This hairdresser",
    "t2": "you recommended",
    "t3": "is a genius!",
    "condition": "literal praise",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Susan was disappointed with the hairdresser.",
    "CorrectResponse": "z",
    "item": "P5",
    data: {item: 'P5', condition: 'literal praise'}
  },
  {
    "s1": "Mike has never been good at maths at school.",
    "s2": "However, when he took part in the national championships in arithmetics, he won the first place.",
    "s3": "His teacher told him:",
    "full_context": "Mike has never been good at maths at school. However, when he took part in the national championships in arithmetics, he won the first place. His teacher told him:",
    "tf_question": "Mike's teacher thinks he is skilled at maths.",
    "t1": "I didn't know",
    "t2": "you were",
    "t3": "a mathematical genius!",
    "condition": "literal praise",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Mike's teacher thinks he is skilled at maths.",
    "CorrectResponse": "{/}",
    "item": "P6",
    data: {item: 'P6', condition: 'literal praise'}
  },
  {
    "s1": "Rick's friend invited him to a rock concert but Rick didn't want to go saying the band is lousy.",
    "s2": "Quite unexpectedly, the band gave an amazing performance and Rick enjoyed the concert immensely.",
    "s3": "After the concert he said to his friend:",
    "full_context": "Rick's friend invited him to a rock concert but Rick didn't want to go saying the band is lousy.Quite unexpectedly, the band gave an amazing performance and Rick enjoyed the concert immensely.After the concert he said to his friend:",
    "tf_question": "Rick thinks the concert was poor.",
    "t1": "See, I told you",
    "t2": "this band",
    "t3": "was lousy.",
    "condition": "ironic praise",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 1600,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Rick thinks the concert was poor.",
    "CorrectResponse": "z",
    "item": "P7",
    data: {item: 'P7', condition: 'ironic praise'}
  },
  {
    "s1": "Sheila was going to introduce her new boyfriend to her parents.",
    "s2": "Before they met she told them that he was an intelligent and cultural man, but when they finally met, her boyfriend just kept telling obscene stories and crude jokes at dinner.",
    "s3": "Sheila's parents said to her:",
    "full_context": "Sheila was going to introduce her new boyfriend to her parents. Before they met she told them that he was an intelligent and cultural man, but when they finally met, her boyfriend just kept telling obscene stories and crude jokes at dinner.Sheila's parents said to her:",
    "tf_question": "Sheila's parents don't like her new boyfriend.",
    "t1": "Your boyfriend",
    "t2": "is the most vulgar man",
    "t3": "we've ever met.",
    "condition": "literal criticism",
    "list": "Practice",
    "tf_question_time": 1800,
    "edt_question_time": 1500,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 1200,
    "Question": "Sheila's parents don't like her new boyfriend.",
    "CorrectResponse": "{/}",
    "item": "P8",
    data: {item: 'P8', condition: 'literal criticism'}
  }
]