var exp_stim_b = [
  {
    "s1": "Afflicted with a mysterious skin condition on his behind, Ross seeks advice from Phoebe's herbalist.",
    "s2": "He feels uneasy about exposing his buttocks to the man, but finally he gets convinced and the herbalist gives him some mysterious ointments.",
    "s3": "After two weeks of applying them regularly, Ross says:",
    "full_context": "Afflicted with a mysterious skin condition on his behind, Ross seeks advice from Phoebe's herbalist.He feels uneasy about exposing his buttocks to the man, but finally he gets convinced and the herbalist gives him some mysterious ointments. After two weeks of applying them regularly, Ross says:",
    "tf_question": "It was Phoebe who recommended the doctor to Ross.",
    "t1": "These ointments",
    "t2": "made my butt",
    "t3": "itch even worse than before!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "It was Phoebe who recommended the doctor to Ross.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d1",
    data: {item: 'd1', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Chandler and Joey are with Monica at the beach, where she gets stung by a jellyfish.",
    "s2": "Joey, who saw a feature on the Discovery Channel, suggests peeing on the sting, but gets scared, so Chandler finally does it.",
    "s3": "Monica says to the guys:",
    "full_context": "Chandler and Joey are with Monica at the beach, where she gets stung by a jellyfish.Joey, who saw a feature on the Discovery Channel, suggests peeing on the sting, but gets scared, so Chandler finally does it.Monica says to the guys:",
    "tf_question": "Phoebe got stung by a wasp.",
    "t1": "It finally stopped burning",
    "t2": "and the swelling",
    "t3": "is nearly gone!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Phoebe got stung by a wasp.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d2",
    data: {item: 'd2', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Chandler is planning to propose to Monica, but he wants it to be a surprise.",
    "s2": "He keeps telling her that he never wants to get married and she starts to believe it and leaves their apartment all in tears, heading to her ex-boyfriend Richard.",
    "s3": "Chandler says to Joey:",
    "full_context": "Chandler is planning to propose to Monica, but he wants it to be a surprise. He keeps telling her that he never wants to get married and she starts to believe it and leaves their apartment all in tears, heading to her ex-boyfriend Richard. Chandler says to Joey:",
    "tf_question": "Chandler is a fierce opponent of marriage.",
    "t1": "I have to catch her",
    "t2": "as soon as possible",
    "t3": "or she'll be gone for good.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 2000,
    "t2_time": 1600,
    "t3_time": 2400,
    "Question": "Chandler is a fierce opponent of marriage.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d3",
    data: {item: 'd3', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Joey and Chandler adopt a baby chick and a duck.",
    "s2": "They are having great fun organising chick and duck races, when Chandler's girlfriend Janice comes to visit him.",
    "s3": "When she sees her boyfriend engaging in such ridiculous activities, she says to Chandler:",
    "full_context": "Joey and Chandler adopt a baby chick and a duck.They are having great fun organising chick and duck races, when Chandler's girlfriend Janice comes to visit him. When she sees her boyfriend engaging in such ridiculous activities, she says to Chandler:",
    "tf_question": "Janice didn't like the idea of keeping chicks and ducks at home.",
    "t1": "I didn't realise",
    "t2": "you've never left",
    "t3": "pre-school!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 400,
    "Question": "Janice didn't like the idea of keeping chicks and ducks at home.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d4",
    data: {item: 'd4', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Joey gets chosen to play the role of Dr. Drake Ramoray, a neurosurgeon on Days of Our Lives after he sleeps with the casting lady.",
    "s2": "However, he makes his friends believe that he\\n got picked only thanks to his remarkable acting skills.",
    "s3": "Chandler says:",
    "full_context": "Joey gets chosen to play the role of Dr. Drake Ramoray, a neurosurgeon on Days of Our Lives after he sleeps with the casting lady.However, he makes his friends believe that he\\n got picked only thanks to his remarkable acting skills. Chandler says:",
    "tf_question": "Joey got picked for the role of Mozart in \"Amadeus\".",
    "t1": "I've never been prouder",
    "t2": "of my best friend Joey",
    "t3": "than today!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Joey got picked for the role of Mozart in \"Amadeus\".",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d5",
    data: {item: 'd5', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Joey gives Chandler an extremely tacky engraved gold bracelet, telling him that this shall be the symbol of their enduring friendship.",
    "s2": "Chandler pretends he likes the bracelet but never wears it which makes Joey suspicious.",
    "s3": "Joey says to Chandler:",
    "full_context": "Joey gives Chandler an extremely tacky engraved gold bracelet, telling him that this shall be the symbol of their enduring friendship. Chandler pretends he likes the bracelet but never wears it which makes Joey suspicious.Joey says to Chandler:",
    "tf_question": "Chandler gave Joey a gold bracelet.",
    "t1": "I can see",
    "t2": "that you're not wearing",
    "t3": "the bracelet.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1600,
    "t3_time": 800,
    "Question": "Chandler gave Joey a gold bracelet.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d6",
    data: {item: 'd6', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Joey is dating Ross's work colleague Charlie who is a paleonthologist too.",
    "s2": "When the whole group goes to Barbados to accompany Ross on a paleonthologists' conference, it quickly turns out that Joey and Charlie have little in common.",
    "s3": "They decide to break up and Joey is in great pain, so to console him Ross says to him:",
    "full_context": "Joey is dating Ross's work colleague Charlie who is a paleonthologist too.When the whole group goes to Barbados to accompany Ross on a paleonthologists' conference, it quickly turns out that Joey and Charlie have little in common. They decide to break up and Joey is in great pain, so to console him Ross says to him:",
    "tf_question": "Charlie is an ophthalmologist.",
    "t1": "Don't worry,",
    "t2": "maybe you two were just",
    "t3": "not meant to be together.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 2000,
    "Question": "Charlie is an ophthalmologist.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d7",
    data: {item: 'd7', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Monica and Chandler decide not to host Thanksgiving but Phoebe convinces them to by appealing to Monica's competitive nature.",
    "s2": "Chandler helps out for the first time by making Cranberry sauce and surprisingly, Monica lets him.",
    "s3": "The sauce is a disaster, but Monica decides to be supportive, so she says to Chandler:",
    "full_context": "Monica and Chandler decide not to host Thanksgiving but Phoebe convinces them to by appealing to Monica's competitive nature. Chandler helps out for the first time by making Cranberry sauce and surprisingly, Monica lets him.The sauce is a disaster, but Monica decides to be supportive, so she says to Chandler:",
    "tf_question": "Chandler doesn't cook very well.",
    "t1": "Don't worry,",
    "t2": "I'll make my own sauce",
    "t3": "in a minute.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 1200,
    "Question": "Chandler doesn't cook very well.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d8",
    data: {item: 'd8', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Monica cooks a gourmet meal for a restaurateur named Steve, who is looking for a new chef.",
    "s2": "Unfortunately, he's stoned and would just as well eat McDonald's french fries as her haute cuisine.",
    "s3": "As a result, Monica doesn't get the job and he says to Rachel:",
    "full_context": "Monica cooks a gourmet meal for a restaurateur named Steve, who is looking for a new chef. Unfortunately, he's stoned and would just as well eat McDonald's french fries as her haute cuisine.As a result, Monica doesn't get the job and he says to Rachel:",
    "tf_question": "Monica prepared french fries to impress the famous restaurateur, Steve.",
    "t1": "I really thought",
    "t2": "I would get",
    "t3": "this job!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Monica prepared french fries to impress the famous restaurateur, Steve.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d9",
    data: {item: 'd9', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Monica decides to pay an unexpected visit to her boyfriend Chandler in Tulsa, where he had moved recently for his new job.",
    "s2": "However, he's watching porn on the hotel television and when she arrives he, in panic, switches channels to a shark documentary.",
    "s3": "He leads Monica to believe the sea creatures turn him on and Monica says to him:",
    "full_context": "Monica decides to pay an unexpected visit to her boyfriend Chandler in Tulsa, where he had moved recently for his new job.However, he's watching porn on the hotel television and when she arrives he, in panic, switches channels to a shark documentary. He leads Monica to believe the sea creatures turn him on and Monica says to him:",
    "tf_question": "Monica visited Chandler in his new apartment in Toledo.",
    "t1": "That simply",
    "t2": "can't be true,",
    "t3": "you must be kidding me!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "Monica visited Chandler in his new apartment in Toledo.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d10",
    data: {item: 'd10', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Phoebe adopts an orphaned rat family and she invites her new boyfriend David, who is a physicist, to her apartment.",
    "s2": "When David finds out she's keeping rats at home, he is terribly scared and lists to Phoebe all the diseases she can possibly contract from her new pets.",
    "s3": "Phoebe refuses to get rid of them and says to him:",
    "full_context": "Phoebe adopts an orphaned rat family and she invites her new boyfriend David, who is a physicist, to her apartment. When David finds out she's keeping rats at home, he is terribly scared and lists to Phoebe all the diseases she can possibly contract from her new pets. Phoebe refuses to get rid of them and says to him:",
    "tf_question": "Phoebe's boyfriend is a physicist.",
    "t1": "I don't need",
    "t2": "your doctor's talk",
    "t3": "at all!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Phoebe's boyfriend is a physicist.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d11",
    data: {item: 'd11', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Phoebe catches chicken pox just as her old flame Ryan arrives in town on leave from the Navy.",
    "s2": "Even though he hasn't yet had chicken pox, he can't stand to be apart.",
    "s3": "They both spend the rest of the time sick trying to not scratch at the sore, and Ryan says to her:",
    "full_context": "Phoebe catches chicken pox just as her old flame Ryan arrives in town on leave from the Navy.Even though he hasn't yet had chicken pox, he can't stand to be apart.They both spend the rest of the time sick trying to not scratch at the sore, and Ryan says to her:",
    "tf_question": "Ryan has never has chicken pox before.",
    "t1": "I'll go to the drugstore downstairs",
    "t2": "and bring us some ointment",
    "t3": "for the sore spots.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 2400,
    "t2_time": 2000,
    "t3_time": 1600,
    "Question": "Ryan has never has chicken pox before.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d12",
    data: {item: 'd12', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Phoebe has been a vegetarian for her entire life, but when she gets pregnant with the triplets she feels compelled to finally start eating meat.",
    "s2": "Hardly a day passes without her eating a huge raw steak.",
    "s3": "She says to her friend Rachel:",
    "full_context": "Phoebe has been a vegetarian for her entire life, but when she gets pregnant with the triplets she feels compelled to finally start eating meat. Hardly a day passes without her eating a huge raw steak. She says to her friend Rachel:",
    "tf_question": "Phoebe is pregnant with triplets.",
    "t1": "These babies",
    "t2": "in my womb",
    "t3": "are definitely carnivore!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Phoebe is pregnant with triplets.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d13",
    data: {item: 'd13', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Phoebe is discovered by a record producer who wants to make her song \"Smelly Cat\" a video, but who secretly dubs in the voice of a more talented woman.",
    "s2": "Phoebe feels betrayed and she promises to take revenge on the producer.",
    "s3": "She tells her friends:",
    "full_context": "Phoebe is discovered by a record producer who wants to make her song \"Smelly Cat\" a video, but who secretly dubs in the voice of a more talented woman. Phoebe feels betrayed and she promises to take revenge on the producer. She tells her friends:",
    "tf_question": "Phoebe is the author of a famous song: \"Smelly Feet\".",
    "t1": "This awful guy",
    "t2": "simply made a fool",
    "t3": "out of me!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1600,
    "t3_time": 1200,
    "Question": "Phoebe is the author of a famous song: \"Smelly Feet\".",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d14",
    data: {item: 'd14', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Phoebe is trying to teach Joey some French for his audition for a theatre play.",
    "s2": "She asks him to repeat the sentence:\"Je m'appelle Claude\", but he keeps mispronouncing it as: \" Je de coup Clow\".",
    "s3": "Phoebe gets irritated and refuses to teach him any longer, saying:",
    "full_context": "Phoebe is trying to teach Joey some French for his audition for a theatre play.She asks him to repeat the sentence:\"Je m'appelle Claude\", but he keeps mispronouncing it as: \" Je de coup Clow\". Phoebe gets irritated and refuses to teach him any longer, saying:",
    "tf_question": "Phoebe is teaching Joey how to speak French.",
    "t1": "I won't teach somebody",
    "t2": "who is utterly",
    "t3": "tone-deaf!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 400,
    "Question": "Phoebe is teaching Joey how to speak French.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d15",
    data: {item: 'd15', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel and Monica had a neighbour upstairs, Mr Heckles, every conversation  with whom broke out into a row.",
    "s2": "However, when he died, he left all his belongings to Monica and Rachel.",
    "s3": "Rachel said to Monica:",
    "full_context": "Rachel and Monica had a neighbour upstairs, Mr Heckles, every conversation  with whom broke out into a row.However, when he died, he left all his belongings to Monica and Rachel.Rachel said to Monica:",
    "tf_question": "Mr Heckles was Monica's grandfather.",
    "t1": "Now I feel so bad",
    "t2": "about us having treated him",
    "t3": "so badly.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 2000,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Mr Heckles was Monica's grandfather.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d16",
    data: {item: 'd16', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel arrives at Central Perk after running away from her wedding to her fiancé Barry and moves into her high school friend Monica.",
    "s2": "When Ross, who's had a crush on Rachel since high school, sees her at Monica's, he starts trying to rekindle their relationship.",
    "s3": "Ross says to Rachel:",
    "full_context": "Rachel arrives at Central Perk after running away from her wedding to her fiancé Barry and moves into her high school friend Monica. When Ross, who's had a crush on Rachel since high school, sees her at Monica's, he starts trying to rekindle their relationship.Ross says to Rachel:",
    "tf_question": "Ross still has feelings for his high school sweetheart Rachel.",
    "t1": "We were really happy",
    "t2": "back then in high school together,",
    "t3": "weren't we?",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 2400,
    "t3_time": 800,
    "Question": "Ross still has feelings for his high school sweetheart Rachel.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d17",
    data: {item: 'd17', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel begins working at Bloomingdale's, an upscale department store chain, and Ross becomes jealous of her colleague, Mark.",
    "s2": "Rachel, tired of the constant accusations of infidelity, decides to break up with him.",
    "s3": "Ross says to Rachel:",
    "full_context": "Rachel begins working at Bloomingdale's, an upscale department store chain, and Ross becomes jealous of her colleague, Mark. Rachel, tired of the constant accusations of infidelity, decides to break up with him.Ross says to Rachel:",
    "tf_question": "Rachel took up a job at Bloomingdale's.",
    "t1": "This is the best proof",
    "t2": "that you've been cheating on me",
    "t3": "with this posh twat called Mark!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 2000,
    "t2_time": 2400,
    "t3_time": 2400,
    "Question": "Rachel took up a job at Bloomingdale's.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d18",
    data: {item: 'd18', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel is going to move to Paris and Ross, realizing  he loves her, chases after her to the airport.",
    "s2": "Rachel realizes she loves him, too, and cancels her flight.",
    "s3": "When the two meet at the airport, she says to him:",
    "full_context": "Rachel is going to move to Paris and Ross, realizing  he loves her, chases after her to the airport.Rachel realizes she loves him, too, and cancels her flight.When the two meet at the airport, she says to him:",
    "tf_question": "Rachel is going to move out ouf New York.",
    "t1": "I want to stay",
    "t2": "with you here",
    "t3": "in New York.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Rachel is going to move out ouf New York.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d19",
    data: {item: 'd19', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel is in labor with Ross's baby and when they are in hospital, Ross's mother gives Ross her engagement ring so that he can propose to Rachel.",
    "s2": "Joey finds Ross's engagement ring on the floor in Rachel's room and he kneels to pick it up.",
    "s3": "Rachel thinks he's proposing and says to him:",
    "full_context": "Rachel is in labor with Ross's baby and when they are in hospital, Ross's mother gives Ross her engagement ring so that he can propose to Rachel.Joey finds Ross's engagement ring on the floor in Rachel's room and he kneels to pick it up.Rachel thinks he's proposing and says to him:",
    "tf_question": "Ross was going to propose to Rachel.",
    "t1": "You're so sweet, Joey,",
    "t2": "let's get married",
    "t3": "right away!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Ross was going to propose to Rachel.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d20",
    data: {item: 'd20', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel is known for her lack of cooking skills, but to  prove her friends wrong, she decided to prepare the most\\ndelicious cake for Thanksgiving.",
    "s2": "However, she mixed up two \\ndifferent recipes and instead of strawberry jam, she put pork\\n into the cake.",
    "s3": "Ross said to the rest of the friends:",
    "full_context": "Rachel is known for her lack of cooking skills, but to  prove her friends wrong, she decided to prepare the most\\ndelicious cake for Thanksgiving.However, she mixed up two \\ndifferent recipes and instead of strawberry jam, she put pork\\n into the cake.Ross said to the rest of the friends:",
    "tf_question": "Rachel prepared a Christmas pudding.",
    "t1": "We need to pretend",
    "t2": "that this is the most",
    "t3": "delicious cake ever!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 1200,
    "Question": "Rachel prepared a Christmas pudding.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d21",
    data: {item: 'd21', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Ross buys himself a pet monkey called Marcel, but  it turns out that he owns it illegally as he doesn't have a permit.",
    "s2": "He decides to give Marcel to a film-making company and the monkey becomes a film star in California",
    "s3": "After Marcel is gone, Ross says:",
    "full_context": "Ross buys himself a pet monkey called Marcel, but  it turns out that he owns it illegally as he doesn't have a permit. He decides to give Marcel to a film-making company and the monkey becomes a film star in CaliforniaAfter Marcel is gone, Ross says:",
    "tf_question": "Ross bought himself a parrot.",
    "t1": "I miss",
    "t2": "my lovely Marcel",
    "t3": "so much!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Ross bought himself a parrot.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d22",
    data: {item: 'd22', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Ross is compelled to make a choice between his childhood crush Rachel and his current lover Julie.",
    "s2": "He asks Joey and Chandler to help him make a list of the pros and cons of each, and he finally chooses Rachel.",
    "s3": "Rachel, however, finds the list and gets angry with Ross and says to him:",
    "full_context": "Ross is compelled to make a choice between his childhood crush Rachel and his current lover Julie.He asks Joey and Chandler to help him make a list of the pros and cons of each, and he finally chooses Rachel.Rachel, however, finds the list and gets angry with Ross and says to him:",
    "tf_question": "Ross chose Rachel over Julie.",
    "t1": "I can't believe",
    "t2": "you could've done",
    "t3": "such a horrible thing to me!",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 2400,
    "Question": "Ross chose Rachel over Julie.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d23",
    data: {item: 'd23', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Ross is preparing for a very important date with his old sweatheart and decides to get a spray-on tan.",
    "s2": "After hearing seemingly straightforward instructions, he gets confused and accidentally gets a double dose on the front of his body and nothing on his back.",
    "s3": "He goes to the date looking ridiculous and the date is a disaster, and after the date he says:",
    "full_context": "Ross is preparing for a very important date with his old sweatheart and decides to get a spray-on tan.After hearing seemingly straightforward instructions, he gets confused and accidentally gets a double dose on the front of his body and nothing on his back. He goes to the date looking ridiculous and the date is a disaster, and after the date he says:",
    "tf_question": "Ross's date didn't like his fake tan.",
    "t1": "I shouldn't have",
    "t2": "got myself this",
    "t3": "spray-on tan.",
    "condition": "distracter",
    "list": "distracter",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Ross's date didn't like his fake tan.",
    "TargetType": "distracter",
    "list_new": "distracter",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "distracter",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "d24",
    data: {item: 'd24', type: 'distracter', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "A new professor was hired to teach philosophy, and he was supposed to be really sharp.",
    "s2": "When Allen asked several questions, the professor offered naive and ignorant answers.",
    "s3": "Allen said:",
    "full_context": "A new professor was hired to teach philosophy, and he was supposed to be really sharp. When Allen asked several questions, the professor offered naive and ignorant answers.Allen said:",
    "tf_question": "Allen thinks the professor is smart.",
    "t1": "That guy",
    "t2": "is brilliant",
    "t3": "at answering questions.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Allen thinks the professor is smart.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp1",
    data: {item: 'exp1', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Alice told her roommate how afraid she was of taking a required calculus class, because she was sure she would fail.",
    "s2": "When the final grades were posted, Alice saw she had received an F.",
    "s3": "Alice turned to her roommate and said:",
    "full_context": "Alice told her roommate how afraid she was of taking a required calculus class, because she was sure she would fail. When the final grades were posted, Alice saw she had received an F. Alice turned to her roommate and said:",
    "tf_question": "Alice thinks her math grade is terrible.",
    "t1": "My math grades",
    "t2": "are bad",
    "t3": "these days.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Alice thinks her math grade is terrible.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp2",
    data: {item: 'exp2', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Alicia and her co-worker were social workers who were sent out to visit a family they were told lived in abject poverty.",
    "s2": "When they arrived they found themselves at a rat-infested broken down tenement building.",
    "s3": "Alicia said:",
    "full_context": "Alicia and her co-worker were social workers who were sent out to visit a family they were told lived in abject poverty.When they arrived they found themselves at a rat-infested broken down tenement building.Alicia said:",
    "tf_question": "Alicia thinks the living conditions are dreadful.",
    "t1": "These living conditions",
    "t2": "are terrible",
    "t3": "to see.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Alicia thinks the living conditions are dreadful.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp3",
    data: {item: 'exp3', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Audrey and her husband went on a discount cruise in the Caribbean and they expected very little because the trip was so cheap.",
    "s2": "When they arrived, they found that the cruise ship was luxurious and their cabin was large and comfortable.",
    "s3": "Audrey said:",
    "full_context": "Audrey and her husband went on a discount cruise in the Caribbean and they expected very little because the trip was so cheap.When they arrived, they found that the cruise ship was luxurious and their cabin was large and comfortable.Audrey said:",
    "tf_question": "Audrey thinks the cruise ship is pleasurable.",
    "t1": "We",
    "t2": "are suffering",
    "t3": "on this cruise.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 400,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Audrey thinks the cruise ship is pleasurable.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp4",
    data: {item: 'exp4', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Beth was looking forward to a fun weekend.",
    "s2": "Late on Friday afternoon, Beth's professor told her that there would be an extra reading assignment for the weekend.",
    "s3": "Beth said:",
    "full_context": "Beth was looking forward to a fun weekend. Late on Friday afternoon, Beth's professor told her that there would be an extra reading assignment for the weekend.Beth said:",
    "tf_question": "Beth thinks she will have a good weekend.",
    "t1": "This weekend",
    "t2": "will be pleasant",
    "t3": "for me.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Beth thinks she will have a good weekend.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp5",
    data: {item: 'exp5', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Bill's brother said he had too little energy to help Bill paint his den.",
    "s2": "When Bill stopped over at his brother's house later that day, his brother was in the middle of a rigorous work-out.",
    "s3": "Bill said:",
    "full_context": "Bill's brother said he had too little energy to help Bill paint his den.When Bill stopped over at his brother's house later that day, his brother was in the middle of a rigorous work-out.Bill said:",
    "tf_question": "Bill thinks that his brother is energetic.",
    "t1": "I see",
    "t2": "you're too tired",
    "t3": "to do much of anything.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 2000,
    "Question": "Bill thinks that his brother is energetic.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp6",
    data: {item: 'exp6', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Bob and a co-worker had to fly to Chicago for an important meeting.The plane was scheduled to land at 5 p.m., just in time to make the meeting.",
    "s2": "Bob was very worried that they would miss the beginning of the meeting, but the plane arrived an hour early.",
    "s3": "His co-worker said:",
    "full_context": "Bob and a co-worker had to fly to Chicago for an important meeting.The plane was scheduled to land at 5 p.m., just in time to make the meeting. Bob was very worried that they would miss the beginning of the meeting, but the plane arrived an hour early. His co-worker said:",
    "tf_question": "Bob's co-worker thinks that they will be late for the meeting.",
    "t1": "We'll be",
    "t2": "awfully late",
    "t3": "for that meeting.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Bob's co-worker thinks that they will be late for the meeting.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp7",
    data: {item: 'exp7', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Cathy was looking for a clean and quiet apartment and the rental agent told her he had found her the perfect apartment.",
    "s2": "The apartment he showed her was light and spacious and located right in a very peaceful neighborhood.",
    "s3": "Cathy said:",
    "full_context": "Cathy was looking for a clean and quiet apartment and the rental agent told her he had found her the perfect apartment.The apartment he showed her was light and spacious and located right in a very peaceful neighborhood.Cathy said:",
    "tf_question": "Cathy thinks the apartment is terrible.",
    "t1": "This apartment",
    "t2": "is a delight",
    "t3": "to my eyes.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Cathy thinks the apartment is terrible.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp8",
    data: {item: 'exp8', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Charlie's friend asked Charlie to meet him for dinner to discuss something important and said that he would be sure to be there at seven sharp.",
    "s2": "Charlie arrived at seven o'clock sharp, but his friend did not appear until eight o'clock.",
    "s3": "Charlie said:",
    "full_context": "Charlie's friend asked Charlie to meet him for dinner to discuss something important and said that he would be sure to be there at seven sharp. Charlie arrived at seven o'clock sharp, but his friend did not appear until eight o'clock.Charlie said:",
    "tf_question": "Charlie thinks his friend arrived late.",
    "t1": "You are",
    "t2": "prompt about",
    "t3": "showing up.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Charlie thinks his friend arrived late.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp9",
    data: {item: 'exp9', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Corrine and a friend went to a new movie even though it had been reviewed as the year's worst picture.",
    "s2": "Both found the movie dull and the ending had them asleep in their seats.",
    "s3": "Corrine said:",
    "full_context": "Corrine and a friend went to a new movie even though it had been reviewed as the year's worst picture. Both found the movie dull and the ending had them asleep in their seats. Corrine said:",
    "tf_question": "Corrine thinks the movie was boring.",
    "t1": "This movie",
    "t2": "was deadly",
    "t3": "as the review said.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1600,
    "Question": "Corrine thinks the movie was boring.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp10",
    data: {item: 'exp10', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Frank's cousin considered himself to be very entertaining.",
    "s2": "One evening he told a story about an ordinary shopping trip to the mall that ended with a robbery and shoot out.",
    "s3": "Frank said:",
    "full_context": "Frank's cousin considered himself to be very entertaining. One evening he told a story about an ordinary shopping trip to the mall that ended with a robbery and shoot out.Frank said:",
    "tf_question": "Frank thinks his cousin's story about the mall is boring.",
    "t1": "Your stories",
    "t2": "are fascinating",
    "t3": "to listen to.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Frank thinks his cousin's story about the mall is boring.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp11",
    data: {item: 'exp11', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Gail's friend asked her to come with her to a lecture on global warming and she went, even though she said she thought it would be of no interest.",
    "s2": "She found the lecture to be fascinating, though, and she wanted to ask lots of questions.",
    "s3": "Gail's friend said:",
    "full_context": "Gail's friend asked her to come with her to a lecture on global warming and she went, even though she said she thought it would be of no interest. She found the lecture to be fascinating, though, and she wanted to ask lots of questions.Gail's friend said:",
    "tf_question": "Gail's friend thinks the lecture was tedious.",
    "t1": "That lecture",
    "t2": "was boring",
    "t3": "as you expected.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Gail's friend thinks the lecture was tedious.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp12",
    data: {item: 'exp12', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Heidi's boss was looking forward to his weekend getaway.",
    "s2": "Just before he was to leave, Heidi arrived at his office with a huge load of documents for him to work on.",
    "s3": "He said:",
    "full_context": "Heidi's boss was looking forward to his weekend getaway. Just before he was to leave, Heidi arrived at his office with a huge load of documents for him to work on.He said:",
    "tf_question": "Heidi's boss thinks he will enjoy his weekend.",
    "t1": "My getaway",
    "t2": "is going to be nice",
    "t3": "this weekend.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Heidi's boss thinks he will enjoy his weekend.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp13",
    data: {item: 'exp13', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "It was Jen's first day at her new teaching job and she heard that the students were excited and interested.",
    "s2": "She had prepared a stimulating lecture, but the students sat looking at their desks and didn't ask a single question.",
    "s3": "Jen said:",
    "full_context": "It was Jen's first day at her new teaching job and she heard that the students were excited and interested. She had prepared a stimulating lecture, but the students sat looking at their desks and didn't ask a single question.Jen said:",
    "tf_question": "Jen thinks the students are bored.",
    "t1": "These students",
    "t2": "are lively",
    "t3": "in class today.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Jen thinks the students are bored.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp14",
    data: {item: 'exp14', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "James asked his roommate for help in chemistry.",
    "s2": "James said he could catch on quickly and indeed it took him two minutes to grasp several complex concepts.",
    "s3": "His roommate said:",
    "full_context": "James asked his roommate for help in chemistry. James said he could catch on quickly and indeed it took him two minutes to grasp several complex concepts. His roommate said:",
    "tf_question": "James' roommate thinks James is learning chemistry quickly.",
    "t1": "Chemistry is",
    "t2": "something you're smart",
    "t3": "at picking up.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "James' roommate thinks James is learning chemistry quickly.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp15",
    data: {item: 'exp15', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "James told his friend he was sure he would fail his first physics exam.",
    "s2": "When the teacher handed back the grades, she announced that James had gotten a perfect score.",
    "s3": "His friend said:",
    "full_context": "James told his friend he was sure he would fail his first physics exam.When the teacher handed back the grades, she announced that James had gotten a perfect score. His friend said:",
    "tf_question": "His friend thinks that James did poorly on the test.",
    "t1": "You totally",
    "t2": "screwed up",
    "t3": "that test.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "His friend thinks that James did poorly on the test.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp16",
    data: {item: 'exp16', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Jane was at her college reunion, where she ran into many old acquaintances.",
    "s2": "All the people she knew in college were friendly and showed a lot of interest in Jane's life.",
    "s3": "Jane said:",
    "full_context": "Jane was at her college reunion, where she ran into many old acquaintances.All the people she knew in college were friendly and showed a lot of interest in Jane's life. Jane said:",
    "tf_question": "Jane thinks going to the reunion was a good idea.",
    "t1": "Coming to this reunion",
    "t2": "was a fabulous",
    "t3": "thing to do.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Jane thinks going to the reunion was a good idea.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp17",
    data: {item: 'exp17', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Jeanne had postponed her holiday shopping until two days before Christmas.",
    "s2": "Her friend didn't want to go shopping with her because she was sure the crowds would be terrible.",
    "s3": "When they arrived at the mall it was filled with last-minute shoppers and Jeanne said:",
    "full_context": "Jeanne had postponed her holiday shopping until two days before Christmas. Her friend didn't want to go shopping with her because she was sure the crowds would be terrible.When they arrived at the mall it was filled with last-minute shoppers and Jeanne said:",
    "tf_question": "Jeanne thinks the mall is empty.",
    "t1": "The mall",
    "t2": "is packed with",
    "t3": "holiday shoppers.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Jeanne thinks the mall is empty.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp18",
    data: {item: 'exp18', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Jennifer said she loved greasy, fattening food.",
    "s2": "When her friend opened Jennifer's fridge to get a snack, she found tofu and vegetables in the refrigerator and fat-free crackers and rice cakes in the cabinet.",
    "s3": "She said:",
    "full_context": "Jennifer said she loved greasy, fattening food. When her friend opened Jennifer's fridge to get a snack, she found tofu and vegetables in the refrigerator and fat-free crackers and rice cakes in the cabinet.She said:",
    "tf_question": "Jennifer's friend thinks that Jennifer eats healthy foods.",
    "t1": "I see",
    "t2": "you eat junk",
    "t3": "these days.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 800,
    "Question": "Jennifer's friend thinks that Jennifer eats healthy foods.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp19",
    data: {item: 'exp19', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Jerome and a friend were at a rock concert.",
    "s2": "Jerome said he had seen pictures of the male lead singer, and he was very unattractive, but when he came on stage, the women in the audience went wild.",
    "s3": "Jerome's friend said:",
    "full_context": "Jerome and a friend were at a rock concert. Jerome said he had seen pictures of the male lead singer, and he was very unattractive, but when he came on stage, the women in the audience went wild.Jerome's friend said:",
    "tf_question": "Jerome's friend thinks that the women are attracted to the singer.",
    "t1": "He is totally",
    "t2": "unappealing",
    "t3": "to the female sex.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 400,
    "t3_time": 1600,
    "Question": "Jerome's friend thinks that the women are attracted to the singer.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp20",
    data: {item: 'exp20', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Joanne always bragged about her looks.",
    "s2": "On New Year's Eve, she wore a new dress that was way too tight and made her stomach stick out.",
    "s3": "Her roommate watched as she paraded in front of the mirror and said to her:",
    "full_context": "Joanne always bragged about her looks. On New Year's Eve, she wore a new dress that was way too tight and made her stomach stick out.Her roommate watched as she paraded in front of the mirror and said to her:",
    "tf_question": "Joanne's roommate thinks that Joanne looks good in her new dress.",
    "t1": "That dress",
    "t2": "looks attractive",
    "t3": "on you.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joanne's roommate thinks that Joanne looks good in her new dress.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp21",
    data: {item: 'exp21', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Joe had a job interview and his friend told him to be well prepared.",
    "s2": "Joe decided to read upon the company before the interview.",
    "s3": "Joe's friend said:",
    "full_context": "Joe had a job interview and his friend told him to be well prepared. Joe decided to read upon the company before the interview. Joe's friend said:",
    "tf_question": "Joe's friend thinks Joe is well prepared for the interview.",
    "t1": "If you really want the job",
    "t2": "that's a great",
    "t3": "way to get it.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 2400,
    "t2_time": 1200,
    "t3_time": 1600,
    "Question": "Joe's friend thinks Joe is well prepared for the interview.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp22",
    data: {item: 'exp22', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Joel and his friend had to go to a bad part of town known for a high crime rate.",
    "s2": "When they arrived they found that the neighborhood was nothing like their own: it was dirty and filled with unsavory looking people.",
    "s3": "Joel said to his friend:",
    "full_context": "Joel and his friend had to go to a bad part of town known for a high crime rate. When they arrived they found that the neighborhood was nothing like their own: it was dirty and filled with unsavory looking people.Joel said to his friend:",
    "tf_question": "Joel thinks the neighborhood is scary.",
    "t1": "This neighborhood",
    "t2": "looks dangerous",
    "t3": "to me.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joel thinks the neighborhood is scary.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp23",
    data: {item: 'exp23', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Joseph said he wouldn't let on about the surprise birthday party on Friday evening for his sister.",
    "s2": "On Friday afternoon, his sister asked him what he was doing that night and Joseph said he was going to her surprise party.",
    "s3": "Later, Joseph's mother said:",
    "full_context": "Joseph said he wouldn't let on about the surprise birthday party on Friday evening for his sister.On Friday afternoon, his sister asked him what he was doing that night and Joseph said he was going to her surprise party. Later, Joseph's mother said:",
    "tf_question": "Joseph's mother thinks that he is poor at keeping secrets.",
    "t1": "You are",
    "t2": "good at",
    "t3": "keeping secrets!",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Joseph's mother thinks that he is poor at keeping secrets.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp24",
    data: {item: 'exp24', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Julie took her boyfriend skiing.He had never been on skis, and he said he was afraid he would look like an oaf.",
    "s2": "On his first run, he just skied gracefully down, turning beautifully and never falling.",
    "s3": "Julie said:",
    "full_context": "Julie took her boyfriend skiing.He had never been on skis, and he said he was afraid he would look like an oaf. On his first run, he just skied gracefully down, turning beautifully and never falling.Julie said:",
    "tf_question": "Julie thinks that her boyfriend is a poor skier.",
    "t1": "You looked",
    "t2": "clumsy",
    "t3": "on that slope.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Julie thinks that her boyfriend is a poor skier.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp25",
    data: {item: 'exp25', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "June took her first roll of film.",
    "s2": "Since she was a beginning photographer, she expected the pictures would come out poorly, but hey came out wonderfully.",
    "s3": "She said to her friend:",
    "full_context": "June took her first roll of film.Since she was a beginning photographer, she expected the pictures would come out poorly, but hey came out wonderfully.She said to her friend:",
    "tf_question": "June thinks she is a gifted photographer.",
    "t1": "I guess",
    "t2": "I'm bad",
    "t3": "at this.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "June thinks she is a gifted photographer.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp26",
    data: {item: 'exp26', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Kelly's classmate asked him to explain the calculus assignment to him.",
    "s2": "Instead of going to a party, Kelly stayed home and explained everything about the homework",
    "s3": "His classmate said:",
    "full_context": "Kelly's classmate asked him to explain the calculus assignment to him. Instead of going to a party, Kelly stayed home and explained everything about the homework His classmate said:",
    "tf_question": "Kelly's classmate thinks Kelly's instruction was useless.",
    "t1": "You are",
    "t2": "helpful",
    "t3": "to have around.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Kelly's classmate thinks Kelly's instruction was useless.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp27",
    data: {item: 'exp27', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Ken reluctantly took an office job as a temp because he really needed money.",
    "s2": "He told his friend the work would probably be mindless and low-level work, but his first assignment was exciting and challenging.",
    "s3": "Ken said to his friend:",
    "full_context": "Ken reluctantly took an office job as a temp because he really needed money. He told his friend the work would probably be mindless and low-level work, but his first assignment was exciting and challenging.Ken said to his friend:",
    "tf_question": "Ken thinks that the temp work is enjoyable.",
    "t1": "This temp work",
    "t2": "was a bad",
    "t3": "choice for me.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Ken thinks that the temp work is enjoyable.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp28",
    data: {item: 'exp28', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Kevin heard that his new roommate was a real stand-up comedian.",
    "s2": "The first day they met, his new roommate made one poor joke after another.",
    "s3": "Kevin said:",
    "full_context": "Kevin heard that his new roommate was a real stand-up comedian.The first day they met, his new roommate made one poor joke after another. Kevin said:",
    "tf_question": "Kevin thinks the jokes are humorous.",
    "t1": "The jokes he tells",
    "t2": "are the funniest",
    "t3": "I've ever heard.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Kevin thinks the jokes are humorous.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp29",
    data: {item: 'exp29', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Marcie bought a used car for a very low price.",
    "s2": "She took it to her mechanic for a tune-up, and told him about the great deal she had gotten on the car.",
    "s3": "After he had checked the car, he told her that it needed a new engine and new brakes, and he commented:",
    "full_context": "Marcie bought a used car for a very low price. She took it to her mechanic for a tune-up, and told him about the great deal she had gotten on the car. After he had checked the car, he told her that it needed a new engine and new brakes, and he commented:",
    "tf_question": "The mechanic thinks Marcie made a bad purchase.",
    "t1": "You got",
    "t2": "a bargain",
    "t3": "on this one.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "The mechanic thinks Marcie made a bad purchase.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp30",
    data: {item: 'exp30', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Marco wanted to attend a lecture about job hunting, but his friend resisted, saying that the talk would be of no help at all.",
    "s2": "Still, Marco dragged his friend along.",
    "s3": "At the lecture, his friend didn't learn anything new, so he said:",
    "full_context": "Marco wanted to attend a lecture about job hunting, but his friend resisted, saying that the talk would be of no help at all.Still, Marco dragged his friend along. At the lecture, his friend didn't learn anything new, so he said:",
    "tf_question": "Marco's friend thinks the lecture was useless.",
    "t1": "Going to that talk",
    "t2": "was a waste of time",
    "t3": "for me.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 2000,
    "t3_time": 800,
    "Question": "Marco's friend thinks the lecture was useless.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp31",
    data: {item: 'exp31', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Maryellen expected to rough it when she went camping on a remote island off the coast of Maine.",
    "s2": "When she arrived, she found camping grounds with no running water and no showers.",
    "s3": "Maryellen said:",
    "full_context": "Maryellen expected to rough it when she went camping on a remote island off the coast of Maine. When she arrived, she found camping grounds with no running water and no showers.Maryellen said:",
    "tf_question": "Maryellen thinks the camping facilities are poor.",
    "t1": "Life is going",
    "t2": "to be primitive",
    "t3": "on this vacation.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Maryellen thinks the camping facilities are poor.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp32",
    data: {item: 'exp32', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Matt was doing his comedy act at a nightclub's amateur night",
    "s2": "His friends had told him that his jokes were always terrific, but during his act the crowd didn't even crack a smile.",
    "s3": "Matt said:",
    "full_context": "Matt was doing his comedy act at a nightclub's amateur night His friends had told him that his jokes were always terrific, but during his act the crowd didn't even crack a smile.Matt said:",
    "tf_question": "Matt thinks his jokes were funny.",
    "t1": "My friends",
    "t2": "were right",
    "t3": "about my jokes.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Matt thinks his jokes were funny.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp33",
    data: {item: 'exp33', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Mike and his friend were watching an interview with a famous artist who  said that his son had exceptional talent in drawing.",
    "s2": "The artist held up a drawing his three-year-old son had made.",
    "s3": "It was stunningly realistic and skillful and Mike said:",
    "full_context": "Mike and his friend were watching an interview with a famous artist who  said that his son had exceptional talent in drawing. The artist held up a drawing his three-year-old son had made. It was stunningly realistic and skillful and Mike said:",
    "tf_question": "Mike thinks the drawing is ordinary for a three-year-old.",
    "t1": "That kid",
    "t2": "is a prodigy",
    "t3": "in the visual arts.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1600,
    "Question": "Mike thinks the drawing is ordinary for a three-year-old.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp34",
    data: {item: 'exp34', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Patty was watching a political debate and one of the candidates said he would take on anyone who cared to argue with him.",
    "s2": "When the candidate's positions were challenged by someone from the audience, he gave an excellent, logical argument.",
    "s3": "Patty said:",
    "full_context": "Patty was watching a political debate and one of the candidates said he would take on anyone who cared to argue with him. When the candidate's positions were challenged by someone from the audience, he gave an excellent, logical argument. Patty said:",
    "tf_question": "Patty thinks the politician is a poor public speaker.",
    "t1": "His debating skills",
    "t2": "are terrific",
    "t3": "to watch and learn from.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 2000,
    "Question": "Patty thinks the politician is a poor public speaker.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp35",
    data: {item: 'exp35', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Peter got caught in a meeting late Friday afternoon and he was tensely expecting really bad traffic on the highway home.",
    "s2": "When he got on the highway he found that the traffic was very heavy and the driving was stop and go.",
    "s3": "Peter said:",
    "full_context": "Peter got caught in a meeting late Friday afternoon and he was tensely expecting really bad traffic on the highway home.When he got on the highway he found that the traffic was very heavy and the driving was stop and go.Peter said:",
    "tf_question": "Peter thinks that the road is empty.",
    "t1": "Traffic",
    "t2": "is terrible",
    "t3": "at this time of day.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 400,
    "t2_time": 800,
    "t3_time": 2000,
    "Question": "Peter thinks that the road is empty.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp36",
    data: {item: 'exp36', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Rachel and a friend were on a gambling trip and they hoped to win a pile of money.",
    "s2": "After one hour, Rachel and her friend had doubled their money.",
    "s3": "Rachel said:",
    "full_context": "Rachel and a friend were on a gambling trip and they hoped to win a pile of money.After one hour, Rachel and her friend had doubled their money. Rachel said:",
    "tf_question": "Rachel thinks gambling is a good way to make money.",
    "t1": "Gambling is",
    "t2": "a great way",
    "t3": "to make money.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Rachel thinks gambling is a good way to make money.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp37",
    data: {item: 'exp37', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Ray postponed going to the DMV to get his driver's license because he hated the long lines.",
    "s2": "When he arrived, he saw at least fifty people ahead of him in line.",
    "s3": "Ray said:",
    "full_context": "Ray postponed going to the DMV to get his driver's license because he hated the long lines.When he arrived, he saw at least fifty people ahead of him in line.Ray said:",
    "tf_question": "Ray thinks the line is short.",
    "t1": "The wait",
    "t2": "is endless",
    "t3": "this morning.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Ray thinks the line is short.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp38",
    data: {item: 'exp38', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Sally and her roommate were having a cook-out.",
    "s2": "The forecast predicted that it would clear up, though it had been overcast all day.",
    "s3": "Just as they started the barbecue, the sun came out, and Sally said:",
    "full_context": "Sally and her roommate were having a cook-out. The forecast predicted that it would clear up, though it had been overcast all day.Just as they started the barbecue, the sun came out, and Sally said:",
    "tf_question": "Sally thinks the weather forecast was accurate.",
    "t1": "The weather forecast",
    "t2": "is on target",
    "t3": "for our cook-out.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 1200,
    "t3_time": 1200,
    "Question": "Sally thinks the weather forecast was accurate.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp39",
    data: {item: 'exp39', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Sam complained to his mother that he had too much homework, which he said would take him the whole weekend.",
    "s2": "On Saturday morning, he started his work, and by the end of the day he had finished less than half.",
    "s3": "His mother said:",
    "full_context": "Sam complained to his mother that he had too much homework, which he said would take him the whole weekend. On Saturday morning, he started his work, and by the end of the day he had finished less than half.His mother said:",
    "tf_question": "Sam's mother thinks that Sam has very little homework to do.",
    "t1": "Your work load",
    "t2": "is overwhelming",
    "t3": "this weekend.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Sam's mother thinks that Sam has very little homework to do.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp40",
    data: {item: 'exp40', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Sandra was very weight-conscious.",
    "s2": "One month, she gained half a pound and she told her friend she was getting fat",
    "s3": "Her friend said:",
    "full_context": "Sandra was very weight-conscious. One month, she gained half a pound and she told her friend she was getting fatHer friend said:",
    "tf_question": "Sandra's friend thinks that Sandra has gained too much weight.",
    "t1": "You are",
    "t2": "so overweight",
    "t3": "these days.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 800,
    "Question": "Sandra's friend thinks that Sandra has gained too much weight.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp41",
    data: {item: 'exp41', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Sarah was looking forward to a pleasant holiday dinner with her entire family.",
    "s2": "At dinner, the conversation began, and by the end, everyone was joyful.",
    "s3": "Sarah said:",
    "full_context": "Sarah was looking forward to a pleasant holiday dinner with her entire family.At dinner, the conversation began, and by the end, everyone was joyful. Sarah said:",
    "tf_question": "Sarah thinks the evening was enjoyable.",
    "t1": "The atmosphere",
    "t2": "is relaxed",
    "t3": "around this table.",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Sarah thinks the evening was enjoyable.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp42",
    data: {item: 'exp42', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Steven's friend said he only read trashy novels because he wasn't smart enough to read serious stuff.",
    "s2": "When Steven went to his friend's apartment, he saw only well-read philosophy books and journals.",
    "s3": "Steven said:",
    "full_context": "Steven's friend said he only read trashy novels because he wasn't smart enough to read serious stuff.When Steven went to his friend's apartment, he saw only well-read philosophy books and journals.Steven said:",
    "tf_question": "Steven thinks that his friend reads easy material.",
    "t1": "You stick to",
    "t2": "lightweight",
    "t3": "books and magazines.",
    "condition": "ironic praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1200,
    "t2_time": 400,
    "t3_time": 1200,
    "Question": "Steven thinks that his friend reads easy material.",
    "TargetType": "ironic praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "ironic",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp43",
    data: {item: 'exp43', type: 'ExperimentalB', valence: 'praise', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Steve's statistics professor had a reputation for giving really difficult exams and refusing to curve the grades.",
    "s2": "The first exam he gave was really hard and no one finished before the hour was up.",
    "s3": "Steve said:",
    "full_context": "Steve's statistics professor had a reputation for giving really difficult exams and refusing to curve the grades. The first exam he gave was really hard and no one finished before the hour was up. Steve said:",
    "tf_question": "Steve thinks the exam was easy.",
    "t1": "That professor",
    "t2": "is tough",
    "t3": "on his students.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Steve thinks the exam was easy.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp44",
    data: {item: 'exp44', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Susan and her roommate were having a party and they thought it would be easy to cook a gourmet meal with a very small budget.",
    "s2": "It turned out that the ingredients were much less expensive than they expected, so they ended up with an excellent dinner.",
    "s3": "Susan's roommate said:",
    "full_context": "Susan and her roommate were having a party and they thought it would be easy to cook a gourmet meal with a very small budget. It turned out that the ingredients were much less expensive than they expected, so they ended up with an excellent dinner.Susan's roommate said:",
    "tf_question": "Susan's roommate thinks the dinner party was a failure.",
    "t1": "Having this dinner party",
    "t2": "on a tight budget",
    "t3": "was a stunning idea!",
    "condition": "literal praise",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 1600,
    "t2_time": 1600,
    "t3_time": 1600,
    "Question": "Susan's roommate thinks the dinner party was a failure.",
    "TargetType": "literal praise",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "praise",
    "ironic": "literal",
    "cresp_EDT": "praise",
    "cresp_EDT_L": "p",
    "cresp_EDT_R": "q",
    "item": "exp45",
    data: {item: 'exp45', type: 'ExperimentalB', valence: 'praise', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "The students in Annette's class all had to do a group project.",
    "s2": "When it was time to get started, they did nothing, and got it done late.",
    "s3": "Annette said:",
    "full_context": "The students in Annette's class all had to do a group project. When it was time to get started, they did nothing, and got it done late.Annette said:",
    "tf_question": "Annette thinks they did a bad job.",
    "t1": "Our planning",
    "t2": "was excellent",
    "t3": "on this project.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Annette thinks they did a bad job.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp46",
    data: {item: 'exp46', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  },
  {
    "s1": "Tim was bringing a friend to the neighborhood block party and he warned his friend that the party would probably be a deadly bore.",
    "s2": "Most of the guests were shy and quiet and said little.",
    "s3": "Tim's friend said:",
    "full_context": "Tim was bringing a friend to the neighborhood block party and he warned his friend that the party would probably be a deadly bore.Most of the guests were shy and quiet and said little. Tim's friend said:",
    "tf_question": "Tim's friend thinks the party was exciting.",
    "t1": "This party",
    "t2": "is dull",
    "t3": "as you predicted.",
    "condition": "literal criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 800,
    "t3_time": 1200,
    "Question": "Tim's friend thinks the party was exciting.",
    "TargetType": "literal criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "false",
    "cresp_TF_L": "q",
    "cresp_TF_R": "p",
    "valence": "criticism",
    "ironic": "literal",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp47",
    data: {item: 'exp47', type: 'ExperimentalB', valence: 'criticism', ironic: 'literal', list: 'b'}
  },
  {
    "s1": "Tony was anxiously awaiting his SAT scores and he knew his parents expected him to do well.",
    "s2": "When his scores arrived, he was pretty upset, because his scores were the lowest in his class.",
    "s3": "Tony said:",
    "full_context": "Tony was anxiously awaiting his SAT scores and he knew his parents expected him to do well. When his scores arrived, he was pretty upset, because his scores were the lowest in his class.Tony said:",
    "tf_question": "Tony thinks that his parents will be disappointed with his scores.",
    "t1": "My parents",
    "t2": "are going to be",
    "t3": "happy about this.",
    "condition": "ironic criticism",
    "list": "ExperimentalB",
    "tf_question_time": 18000,
    "edt_question_time": 15000,
    "t1_time": 800,
    "t2_time": 1600,
    "t3_time": 1200,
    "Question": "Tony thinks that his parents will be disappointed with his scores.",
    "TargetType": "ironic criticism",
    "list_new": "expB",
    "version": "b",
    "cresp_TF": "true",
    "cresp_TF_L": "p",
    "cresp_TF_R": "q",
    "valence": "criticism",
    "ironic": "ironic",
    "cresp_EDT": "criticism",
    "cresp_EDT_L": "q",
    "cresp_EDT_R": "p",
    "item": "exp48",
    data: {item: 'exp48', type: 'ExperimentalB', valence: 'criticism', ironic: 'ironic', list: 'b'}
  }
]